### PR TITLE
[Qt] Anti-Phishing: Network Dialog Whitelist and Blacklist (user editable)

### PR DESCRIPTION
**Pull request by cculianu**
This addresses #1065.

The rationale for this new facility is that we want the user to be able to guard against sybil attacks. As such, we now offer a facility to specify "white listed" servers, as well as have the user manually specify the previously internal-only server blacklist.

Highlights:

- White-list is called "**Default server**" in the GUI to make it a very neutral term (suggested by im_uname).
- The "white listing" facility is **ONLY** used If the user has "Connect to default servers only" checked. *This option is off by default.*
- The white list is fully user-editable
- The default white-list are the servers specified in the `servers.json` file
- The user may also elect to manually blacklist servers (previous to this, the blacklist was managed internally for servers that were otherwise misbehaving) -- this brings the internal-only blacklist into full view in the UI.
- User may clear the entire blacklist with a couple of clicks in the GUI
- User may manually add/remove servers individually to/from the blacklist
- Blacklisted servers can never be connected to (unless they are unblacklisted).

---

Here are some screen shots: 

screen shot 2019-01-09 at 8 00 47 pm
screen shot 2019-01-09 at 8 01 28 pm
screen shot 2019-01-09 at 8 01 22 pm
screen shot 2019-01-09 at 8 01 43 pm
screen shot 2019-01-09 at 8 01 11 pm
screen shot 2019-01-09 at 8 01 02 pm

---

### CODE REVIEW

**Comment by markblundeberg** [comment]
Looks amazing!

I dislike the name 'default' for these servers since the defaults can be modified... I'll see if I can think of something better.

**Comment by imaginaryusername** [comment]
Seems to work! The icons look a little... ambiguous to me though. If we want to avoid putting in more icons, perhaps we can use ✔ (U+2714) and ⛔ (U+26D4) seems just as old as ⌘ (U+2318) and ⌧ (U+2327), no? 

But I'm fine either way. 

@markblundeberg Default was the most neutral term I could think of that fits yet doesn't indicate developer bias...maybe alternatives could be "Preloaded" or "Known", but both seems a little clunky to me. See if you got anything!

**Comment by markblundeberg** [comment]
OK I had an idea -- use the term "whitelisted". However, when the user first enables "Use whitelisted servers", you pop up a dialog that says something to the effect of "*I am going to pre-populate your whitelist with the built-in default server list, but you can edit it.*"

**Comment by imaginaryusername** [comment]
If we use "whitelisted" we'll probably want to remove the indicator prior to people checking the "Whitelist servers and use them only" box, lest it gives a strong impression that we're handing out some whitelist. 

Idk, I'll avoid the term altogether, it's a big flame bait.

**Comment by cculianu** [comment]
Well the symbols I picked are from Unicode 1.1 (1993) so they work on ancient windows xp.  

⛔is from 2009.  I haven't even tried it on Windows XP (I have an XP VM somewhere archived but I'm too lazy to fire it up).

I actually like ⛔ a lot for blacklisting -- but the problem is it actually breaks formatting with Qt for some reason for the tree list widget-- the servers in the tree widget box end up not being evenly spaced anymore if that icon is present and it bugs the hell out of me visually.  It looks like "my first app", a student project from someone taking coding 101.   It also breaks formatting and for the "help info" popups.  At least on my mac it does.

I agree the icons are ambiguous.

Personally I'm in favor of white-listing.  That is what it is.  It's a white list.  Call a spade a spade.  Honest language is a strong preference of mine, if you ask me. :)  I'd be surprised if we get flamed for it. I would be surprised if even anyone noticed, really, enough to flame us.  I think the haters don't even actually bother to run our software -- they just run their mouths.

But I am ok with whatever other term as well.  Whatever you guys want.

**Comment by cculianu** [comment]
Re: the "whitelist" term -- that being said it feels a little centralized to use that term. I can see more people checking it out of paranoia if we use that term and then new servers get 0 users.

I'm torn.  No idea what to do here terminology-wise.

Default is a good term but Mark does point out its ambiguity/confusingness.  

Gah.

**Comment by imaginaryusername** [comment]
How does "known" sound?

**Comment by cculianu** [comment]
Hmm. "Known" is also misleading.  The client knows of more servers than the "known" servers.  That do you call the ones that are known, but aren't "known"? Hmm? :D

I say we take this to reddit. Why don't I post on reddit and see what the community says.

Hopefully this thread won't explode too hard. :)

**Comment by markblundeberg** [comment]
It's a whitelist, but as @imaginaryusername says the whitelisting symbols should be hidden from user until they enable the checkbox (since they have no effect). Once enabled, that's when the whitelist actually gets 'set up' from the user's point of view.

The whitelist has nothing to do with default list except that it gets initially populated with the default list. BTW, some thought should be put into how the whitelist will evolve / stay same when new versions come out (with a new default list).

**Comment by cculianu** [comment]
> BTW, some thought should be put into how the whitelist will evolve / stay same when new versions come out (with a new default list).

I did put some thought into it.  My approach was that the new default list "wins" in that if a server is taken off the list, it will disappear from the user's custom list (even if they manually removed/added it themselves).  I used some weird set logic to accomplish that.

If the user adds a server to the list manually and it never appears in servers.json or disappears from servers.json, then they are fine.

It's only if a server WAS in servers.json at some point then gets removed later that the servers.json file "wins".  I did it this way to allow us to "rescind" the "noble status" of being in the default white-list.

As for your other comments.. I'll think on it.  I fear it:

1. is a bitch to implement (already this code feels complicated for what it does).

2. May not be that clear UI-side or that much of a "win".  I dunno.

**Comment by BigBlockIfTrue** [comment]
May I suggest:

* Banned servers
* Preferred servers

I think this is clearer than having both a blacklist and a whitelist. It also allows you to use the preferred servers when not in preferred-only mode (e.g. at least n of the connected servers must be preferred).

**Comment by BigBlockIfTrue** [comment]
May I suggest:

* Banned servers
* Preferred servers

I think this is clearer than having both a blacklist and a whitelist. It also allows you to use the preferred servers when not in preferred-only mode (e.g. at least n of the connected servers must be preferred).

**Comment by cculianu** [comment]
@BigBlockIfTrue -- I really like your suggestion.  I'm trying it out now.  I'm inclined to go with it. It solves a few problems:

1. "Preferred" is a pretty neutral word.  It doesn't have the problems that "white-list" does as @markblundeberg  suggested whereby we would then need to hide the feature until it's turned on to not appear too centralized/draconian.
2. "Banned" is actually a word already used in other wallets (the original Bitcoin Qt wallet uses that term for misbehaving peers).  It's a word that most people understand and in some ways is superior to 'blacklist'.

I'm trying it out now, along with some icon changes!

**Comment by cculianu** [comment]
Update: I love @BigBlockIfTrue 's suggestion!  Here's what it looks like:

screen shot 2019-01-11 at 9 11 12 am

I feel it kills 2 birds with 1 change.  Also note that another reddit user suggested graying-out the servers that aren't being used now for the current mode (this change incorporates that).

i also updated the "Preferred server" unicode char to: "★"
The "banned server" unicode character is now: ⛔

Both of these characters have sufficiently ancient OS support so that our users on ancient versions of Windows should be OK.

Let me know what you guys think!  I'm heavily inclined to go with this scheme!!

**Comment by cculianu** [comment]
>  (e.g. at least n of the connected servers must be preferred).

I like this idea. We probably won't add it to this PR just to keep it short and sweet but that's definitely a config option we should add in the future.  Really good stuff.

**Comment by markblundeberg** [comment]
What this looks like in Linux:

1. The "current server" emoji thing:
  screenshot from 2019-01-11 15-41-40

2. The second tab and its blacklist window:
  screenshot from 2019-01-11 15-42-40

A question... why is it that only one of the three blacklisted servers appears in my second tab? Is that because it's currently being mentioned in 'peers' lists whereas the other servers are not?

**Comment by cculianu** [comment]
Wow. This looks very good on Linux. The formatting is perfect.  On Mac for some reason the "No Entry" icon is a bit too fat and it breaks up text slightly.  On linux it's perfect.

**Comment by cculianu** [comment]
> I really like this, it works well and it's clean design. 110% approval. :-D
> 
> By the way, you learn something new about git every day. Did you know with github you can check out a pull request locally with this syntax? I had no idea until today:
> 
> ```
> git fetch origin pull/1098/head:calinpullreq
> ```

I had no idea either! Thanks for that!

**Comment by cculianu** [comment]
Also:

> A question... why is it that only one of the three blacklisted servers appears in my second tab? Is that because it's currently being mentioned in 'peers' lists whereas the other servers are not?

Yes.

**Comment by jcramer** [comment]
@cculianu this is pretty slick! 

This branch is now merged into EC-SLP master for this release 3.4.3.

https://github.com/simpleledger/Electron-Cash-SLP/commit/e31cbb6d80058e619c14e97828116b065e447cfb

**Comment by cculianu** [comment]
@jcramer OMG.  You merged it before us?! Ok I'm merging!

**Pull request merged**
