### PR TITLE
Build: Update the Wine build docker container to use the MSVC compiler

### PR DESCRIPTION
**Pull request by EchterAgo**
This allows us to build Python modules that need a compiler for Windows.

This increases the size of the Docker image to 11.5GB.

### CODE REVIEW

**Comment by EchterAgo** [comment]
Note that I upgraded setuptools to version 62, not sure if it is needed, but I wanted to test MSVC detection with the latest version. This also upgrades the base image to Ubuntu 22.10.

**Comment by EchterAgo** [comment]
closes #2418

**Comment by EchterAgo** [comment]
I'll have a look into decreasing the Docker image if this is merged. From what I can tell there is still quite a bit in the image that is not needed to run the compiler.

**Comment by cculianu** [comment]
This is heroic.  The fact that we couldn't install python modules that required compilation for the Windows build limited our choices as far as packages and features were concerned.  This truly liberates Electron Cash to be able to leverage any potential Python module it wants for all platforms.  I cannot thank you enough for this.  I know it was a torturous process of troubleshooting to get this work completed.  

I commend you are your persistence and cleverness here.  Truly heroic work!!

**Comment by cculianu** [comment]
Regarding setuptools-62.0.0 -- I have a vague recollection that one of the PyInstallers (the MacOS one probably) breaks on too-new setuptools.  I will also test macOS building to ensure that is not the case... and if it is to take an alternate path for the macOS case.

I am starting up my build(s) now...

**Comment by cculianu** [comment]
Note on building on docker for linux if using Debian 10.
---

I am leaving this note here as a reference in case others have this problem.  I encountered a bug **in docker** itself. See related stackoverflow thread: https://stackoverflow.com/questions/66319610/gpgh

The error output was:

```
calin@debian:~/dev/Electron-Cash$ GIT_REPO=`pwd` ./contrib/build-wine/build.sh docker_msvc
💬 INFO:  Picked up override from env: GIT_REPO=/home/calin/dev/Electron-Cash
~/dev/Electron-Cash ~/dev/Electron-Cash
💬 INFO:  Using docker: Docker version 18.09.1, build 4c52b90
💬 INFO:  Creating docker image ...
Sending build context to Docker daemon  13.82kB
Step 1/29 : FROM ubuntu:21.10@sha256:74fd1c59ac5d29527f56a9ac22753571ce4c40a301d083a56d963bde98a7dfdc
 ---> 54cb245b9a81
Step 2/29 : ARG UBUNTU_MIRROR=http://archive.ubuntu.com/ubuntu/
 ---> Using cache
 ---> fe411a0bb1ea
Step 3/29 : ENV LC_ALL=C.UTF-8 LANG=C.UTF-8
 ---> Using cache
 ---> f2518180cb60
Step 4/29 : ENV UBUNTUDIST=impish
 ---> Using cache
 ---> 1065c58601cb
Step 5/29 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> e2d40b7990ff
Step 6/29 : RUN echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST} main restricted universe multiverse > /etc/apt/sources.list &&     echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST}-updates main restricted universe multiverse >> /etc/apt/sources.list &&     echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST}-backports main restricted universe multiverse >> /etc/apt/sources.list &&     echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST}-security main restricted universe multiverse >> /etc/apt/sources.list &&     dpkg --add-architecture i386 &&     apt-get update -q &&     apt-get install -qy         gnupg2=2.2.20-1ubuntu4         ca-certificates=20210119ubuntu1         wget=1.21-1ubuntu3         git=1:2.32.0-1ubuntu1         p7zip-full=16.02+dfsg-8         make=4.3-4ubuntu1         autotools-dev=20180224.1+nmu1         autoconf=2.69-14         libtool=2.4.6-15         gettext=0.21-4ubuntu3         autopoint=0.21-4ubuntu3         mingw-w64=8.0.0-1         mingw-w64-tools=8.0.0-1         win-iconv-mingw-w64-dev=0.0.8-4
 ---> Running in e7d2e8a9d476
Get:1 http://archive.ubuntu.com/ubuntu impish InRelease [270 kB]
Err:1 http://archive.ubuntu.com/ubuntu impish InRelease
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Get:2 http://archive.ubuntu.com/ubuntu impish-updates InRelease [115 kB]
Err:2 http://archive.ubuntu.com/ubuntu impish-updates InRelease
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Get:3 http://archive.ubuntu.com/ubuntu impish-backports InRelease [101 kB]
Err:3 http://archive.ubuntu.com/ubuntu impish-backports InRelease
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Get:4 http://archive.ubuntu.com/ubuntu impish-security InRelease [110 kB]
Err:4 http://archive.ubuntu.com/ubuntu impish-security InRelease
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Reading package lists...
W: GPG error: http://archive.ubuntu.com/ubuntu impish InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu impish InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu impish-updates InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu impish-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu impish-backports InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu impish-backports InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu impish-security InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu impish-security InRelease' is not signed.
The command '/bin/sh -c echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST} main restricted universe multiverse > /etc/apt/sources.list &&     echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST}-updates main restricted universe multiverse >> /etc/apt/sources.list &&     echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST}-backports main restricted universe multiverse >> /etc/apt/sources.list &&     echo deb ${UBUNTU_MIRROR} ${UBUNTUDIST}-security main restricted universe multiverse >> /etc/apt/sources.list &&     dpkg --add-architecture i386 &&     apt-get update -q &&     apt-get install -qy         gnupg2=2.2.20-1ubuntu4         ca-certificates=20210119ubuntu1         wget=1.21-1ubuntu3         git=1:2.32.0-1ubuntu1         p7zip-full=16.02+dfsg-8         make=4.3-4ubuntu1         autotools-dev=20180224.1+nmu1         autoconf=2.69-14         libtool=2.4.6-15         gettext=0.21-4ubuntu3         autopoint=0.21-4ubuntu3         mingw-w64=8.0.0-1         mingw-w64-tools=8.0.0-1         win-iconv-mingw-w64-dev=0.0.8-4' returned a non-zero code: 100
🗯  ERROR:  Failed to create docker image
```

The solution was to **delete** the `docker.io` package installed bu my Debian 10 distro and manually install the docker from dockerhub.com like so:

```bash
$ sudo apt remove docker.io
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh
```

**Comment by EchterAgo** [comment]
https://ec.loping.net/4.2.7-9-gb29c13722/

from my build server. AppImage build fails due to libusb in combination with new setuptools.

**Comment by cculianu** [comment]
I built this from commit `b29c1372289394d0f326bacaaf88a1d9742bd571`  on 2 completely different docker environments: a Debian 10 host and a macOS host.  I *different* hashes for both. However, the produced binaries run ok (tested on Windows10). Note that the issue with WINE based build not being reproducible if using a macOS-based docker host is **not new to this PR**.  It's likely related to the `*.dist-info` and `*.egg-info` files for packages being different because of macOS filesystem quirks.


Linux-based build:
```
dc1be1aee46bedb77cf092ad9cc8a2d56c7ee7839448f7c00cd01933c0f2194e  Electron-Cash-4.2.7-9-gb29c13722-portable.exe
4bb0435bc0d516451812c39c897fca7dc1ab164ab7a4d90373e5c23625185e5a  Electron-Cash-4.2.7-9-gb29c13722-setup.exe
fbeb867e78266477ee08804d6ab84649474640601440882828345bb02b9f63f2  Electron-Cash-4.2.7-9-gb29c13722.exe
```

macOS-based build:
```
67e714592c2003a6038f67c57c8aa2417a0ec1844627a8376259bf600ca50a61  Electron-Cash-4.2.7-9-gb29c13722-portable.exe
3df67fb6b277a073cf7bbc9982046714e718fc86d8de65d603d2c06e5a1ed7ab  Electron-Cash-4.2.7-9-gb29c13722-setup.exe
269f74866d5d4351fde133e2b05c42803c1849348be0c16605911a14edc4aa31  Electron-Cash-4.2.7-9-gb29c13722.exe
```

**Comment by cculianu** [comment]
Note: we noticed hashes differ now even if using a Linux host (this is new).  Axel is working on bringing back determinism.

Also note that Linux build now fails but I will fix this with a subsequent commit.  I am merging this now so we can move forward.  Thanks @EchterAgo for this great work!

**Comment by rt121212121** [comment]
Nice work.

**Pull request merged**
