### PR TITLE
WIP: [fusion] Increase 'fuzz fee' to be tier/10^6

### PR DESCRIPTION
**Pull request by markblundeberg**
Since the server is now going up to 8 BCH tier level, it makes sense to start paying closer attention to this.

### CODE REVIEW

**Comment by markblundeberg** [comment]
@fyookball we talked about upping the fee fuzzing due to higher tiering, this is basically how to do it. I'm not sure this is exactly the mechanism we want, though, so let's discuss.

**Review by fyookball — COMMENTED** [review]
I am wondering if there's any potentially bad scenarios where a malicious or badly configured server sends insanely high tiers which then causes the max fee to be huge.  

The code seemed to be checking if fuzz_fee was less than fuzz_fee_max_reduced, and fuzz_fee_max_reduced was in turn calculated from fuzz_fee_max, but fuzz_fee_max is the variable we need to have a safety check on.  So maybe i'm getting confused but it seems like the saftey check might not be working anymore.  Previously the min() function ensured an actual saftey check.

**Comment by markblundeberg** [comment]
Hmm that's a good point, we should double check the safeties.
The main safety check is unchanged:

```
            fuzz_fee_max_reduced = min(fuzz_fee_max,
                                       MAX_EXCESS_FEE - self.min_excess_fee,
                                       self.max_excess_fee - self.min_excess_fee)
```

We do have `MAX_EXCESS_FEE` which is (as of now) 10000 sat. With this patch, it would be the maximum random fee for a 100 BCH tier.

If people started to fuse at 1000 BCH tier for instance, then we would want 100k sat fees, so maybe we should increase `MAX_EXCESS_FEE` too.

The server itself also sends `.max_excess_fee` which is currently 300k sats, which would make it so going above 3000 BCH tier would be a problem. However the server could also send a smaller value of `.max_excess_fee` (like 20 sats) which maybe the client should protect against, because if they used such small random fees then the same linkage problem would appear.

(Note that going well beyond 300k sats could mean a problem in that transactions may start to have more than 0.1 BCH in total fees, which would be rejected by `sendrawtransaction` on many electrum servers.)

**Comment by fyookball** [comment]
Ah ok.. yeah the main check looks good. MAX_EXCESS_FEE still the boss.

**Comment by cculianu** [comment]
This is still marked WIP

**Pull request merged**
