### PR TITLE
remove lib/enum.py and replace with Python's enum

### PR DESCRIPTION
**Pull request by markblundeberg**
requirement: python >= 3.4
https://docs.python.org/3/library/enum.html

Also, I've reformatted the only object that used this.

This was a major pet peeve of mine -- every time I would try to start IPython inside the lib directory, it would crash due to trying to import enum (it would import the EC version instead of the system version). Now I was seeing another crash with ctypes trying to import enum! Argh. Anyway, this is more pythonic.

### CODE REVIEW

**Comment by markblundeberg** [comment]
testing now .. something seems mysteriously broken, will get back on that :sweat_smile:

**Comment by cculianu** [comment]
This is so much more elegant.  THANK YOU.  I wasn't aware of this built-in Python class.  It's C++ish.. but it's good.

I've been busy moving (changing apartments) this weekend. I'll review this Monday at the latest I think.  It looks good but I need to spend a little time with when rested just to make sure. :)

Thanks!

**Comment by markblundeberg** [comment]
no rush :-)

**Comment by cculianu** [comment]
This looks great. Sorry it took me so long.  I with Python allowed this data structure auto auto-increment the enum when defining it -- but considering it has reverse-lookup and lookup and name built-in.. at least there's that.  It also appears to auto-convert easily to bytes, etc.

I didn't verify that all the opcode values are correct, though -- but I did visually run through them and they seem correct. 

Since you're the op-code script expert I'm relying on you for that.  They are correct.. right?!

Ok.. merging.

**Comment by fty48jj19** [comment]
e  todos vc s pode ver que q estou mim desepenhado para torna melhor para vcs todos  obrigado um forte abraço para todos,

**Comment by markblundeberg** [comment]
Yeah what I did was to take the Bitcoin-ABC C++ enum, then remove all the semicolons, replace all // with #, and that was the result. :-D

**Comment by fty48jj19** [comment]
vc  tem todos diratorio de dados ai  aconpanha  eu coloquei para todos  para nao se perde  vc tem analizar algo de senha  algo que ficou faltano talves vc esqueceu  entre no no arquivo de dados ler  quias sao novas  talves vc jogou data errada senha  isso encrui em tudo veja se consegue ai  procure verifica ai algo ai esta errado  porque todo colaboradore esta voltano  se vc nao acha o certo mim comenta q vou tenta resolver para vc ok,

**Comment by cculianu** [comment]
@markblundeberg awesome man.  Ha! I did that a lot too when implementing iOS (took objective-c enums and brought them into python in exactly the same way although I didn't know about the IntEnum type). 

Yeah ok so it's definitely good. :)

👍

**Comment by fty48jj19** [comment]
e   ok  obrigado pelo comentario   ,

**Pull request merged**
