### PR TITLE
Remove pip from requirements files

### PR DESCRIPTION
**Pull request by mhsmith**
`--all` was added to the `pip freeze` command line in https://github.com/spesmilo/electrum/commit/10a0b0ad7f97666143e3172542970f765c54ecfd because `protobuf` depends on `setuptools`. However, this also causes `pip` to be unnecessarily included in the requirements files, which increases the app size by [1.4 MB](https://pypi.org/project/pip/#files).

### CODE REVIEW

**Comment by cculianu** [comment]
Thanks for this. Shamefully I say python packaging chaos did not get all of the love it deserved from me. 

Reduction in binary size is always awesome.

Thanks.

Will review/merge later when at computer.

**Comment by EchterAgo** [comment]
I made a build of AppImage & .exe:

https://ec.loping.net/4.0.9-dev5-17-g5cec7ca49/

Only the -setup.exe has changed size and is now 2353 bytes larger. Last build for comparison:

https://ec.loping.net/4.0.9-dev5-16-g55751b4ff/

**Comment by EchterAgo** [comment]
Files work. The only actual difference I have seen is that the `usr/bin/pip` command is not installed in the AppImage anymore, while the same script is still available as `usr/bin/pip3`. The only difference in the .exe files is the PyInstaller tag.

**Comment by mhsmith** [comment]
The log files show that the build process installs pip separately, so this won't have any effect on the Linux and Windows builds. However, it will help Android, and presumably iOS as well.

**Comment by cculianu** [comment]
I guess  we could explicitly remove setuotools and pip (and anything else not needed) in the build.sh for Linux, Windows & OS X if we wanted to be really ambitious...

**Comment by mhsmith** [comment]
`setuptools` is actually needed, as explained above.

**Comment by cculianu** [comment]
> `setuptools` is actually needed, as explained above.

I think only if recompiling the protobuf files to native (.so). I’m like 85% sure our precompiled .py files would work but yeah...it would be like a forced remove.. and unorthodox. thanks for the tip.

**Comment by cculianu** [comment]
(I say this because I have this vague memory of manually ripping out setup tools at one point from the iOS app and being surprised it still worked)...

**Comment by mhsmith** [comment]
Yes, it's probably not really needed, but it's safer to just respect the declared requirements of a third-party package.

pip, on the other hand, is not declared as a requirement of anything, it's just included in the list because of the limitations of `pip freeze`.

**Comment by cculianu** [comment]
Right on.

If anything Windows will build faster not needing to install pip twice.. that always irked me a little, heh.

Thanks @EchterAgo for investigating.. I naively assumed some magic would happen and they would be smaller. Heh.

**Comment by EchterAgo** [comment]
Yea, the AppImage already explicitly removes the pip package and I guess on Windows PyInstaller is smart enough to not include it.

**Comment by cculianu** [comment]
Oh woah -- that's awesome.  After having hit a bunch of bugs with PyInstaller in the last 2 months, I am still impressed at how smart it otherwise is.  👍

**Pull request merged**
