### PR TITLE
coinchooser: "privacy" policy now prefers confirmed coins

### PR DESCRIPTION
**Pull request by gasull**
This is a backport of https://github.com/Electron-Cash/Electron-Cash/commit/2a3c41b24fec278fbe2d7a252095223b11141148, removing the SegWit-related code.

---
This change is [Reviewable](https://reviewable.io/reviews/electron-cash/electron-cash/2092)

### CODE REVIEW

**Comment by gasull** [comment]
I tested this with `--testnet` and works for me.

Please review carefully and test it, since I'm still new to the code.

**Comment by gasull** [comment]
https://github.com/Electron-Cash/Electron-Cash/commit/2a3c41b24fec278fbe2d7a252095223b11141148 is an old commit from 3 years ago, soon after the codebases started to diverge.  Still, I think it's worth it to have this code because it improves the coin selection algorithm.

**Comment by fyookball** [comment]
This seems to complicate the coinchooser logic and I'm not sure the privacy benefits are worth it.  A preference for confirmed coins would help avoid timing-based analysis, but CashFusion already only fuses confirmed coins and in the near future, coinchoosing will be done in conjunction with the status of whether coins have been fusioned.

**Comment by gasull** [comment]
> I'm not sure the privacy benefits are worth it.

Privacy isn't the only benefit.  Confirmed coins can be spent right away, improving the user experience.

**Comment by fyookball** [comment]
Confirmed coins can already be spent right away.

**Comment by gasull** [comment]
> Confirmed coins can already be spent right away.

As far as I know, confirmed coins aren't selected by default.  This code changes that.

**Comment by fyookball** [comment]
Confirmed coins aren't prioritized, but they are selected (unless the user specifically turns on the "Spend only confirmed coins" option.

**Comment by fyookball** [comment]
@markblundeberg @cculianu

**Comment by cculianu** [comment]
I'll look at this in detail hopefully tomorrow. Without studying the code I have no opinion either way on benefits/drawbacks.. so, I will review.

---

As a side note, and unrelated to this PR:

One pet peeve we all have is how the coin chooser does this rounding of amounts to try and make them all the same -- which ends up making it so that fees are not exactly what the user specified. This privacy feature is more annoying than it is private, seems to be the general opinion of users I talked to. (It basically takes some amount from coins to make them all the same change output, if it can, and gives them to fees).  I forget if we ever fixed that.... I seem to remember it still does that.. :/  Again, not really related to this PR, just thought I'd mention it.

I will review this and let you guy know what I think...

**Comment by markblundeberg** [comment]
Yeah I'm not sure what benefits this adds ... 

Commit and PR (note this was from https://github.com/spesmilo/electrum/pull/3496) don't seem to include any explanation about benefits, besides that it makes the privacy coinchooser the default (but this has already happened in EC).

**Comment by markblundeberg** [comment]
Regarding conf coins it's worth pointing out what the Core-derived fullnode wallets do, btw (when you do sendtoaddress and such). Namely they have a notion of 'safe' unconfirmed coins, which are those which have been created by the wallet itself (i.e. the inputs of the unconf tx belong to the wallet), versus 'unsafe' unconfirmed coins which have been received from others. By default the wallet will spend confirmed & unconfirmed-safe coins, and will never spend unconfirmed-unsafe coins.

The reason for this is of course that spending from unsafe coins risks that someone might mine a conflicting tx and thus cancel your tx. For 'safe' unconf txes, that can only happen if the tx is malleated.

So in that sense, this proposed patch has a similar effect though it is indiscriminate about safe/unsafe.

**Comment by gasull** [comment]
@markblundeberg wrote:
> what the Core-derived fullnode wallets do [...]. By default the wallet will spend confirmed & unconfirmed-safe coins, and will never spend unconfirmed-unsafe coins.
>
> this proposed patch has a similar effect though it is indiscriminate about safe/unsafe.

I think the benefit for usability was very clear.

**Pull request closed without merging**
