### PR TITLE
Windows: Add manifest and upgrade PyInstaller to 3.5

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by EchterAgo** [comment]
Note that PyInstaller does not understand the `longPathAware` setting yet and strips it out of the manifest.

**Comment by EchterAgo** [comment]
I've uploaded a test build here: https://ec.loping.net/ichundes/

**Comment by EchterAgo** [comment]
image

**Comment by EchterAgo** [comment]
image

**Comment by cculianu** [comment]
Kind of annoying how pyinstaller messes with the manufest. Grr.

The manifest makes it into the wrapped executable right so it's also in the installed exe?

**Comment by EchterAgo** [comment]
No, it is not in the installed .exe, due to exclude_binaries=True, but it is installed as `Electron-Cash.exe.manifest`, which Windows will also use.

**Comment by EchterAgo** [comment]
image
From the -setup.exe

**Comment by cculianu** [comment]
Oh, awesome. Ok. Perfect.

**Comment by EchterAgo** [comment]
I'll do some testing on Windows 7 and Windows 8.

**Pull request merged**
