### PR TITLE
Copyright headers

### PR DESCRIPTION
**Pull request by PiRK**

### CODE REVIEW

**Comment by PiRK** [comment]
Sorry about this. Not sure why this happened, i probably clicked to fast on  "Create Pull Request" before the target repository was taken into account.

**Comment by cculianu** [comment]
Oh, ha. No worries. I guess you have your source dir pointed to both repos. It happens. 👍

**Comment by PiRK** [comment]
Yes, I cloned Electron-Cash first as PiRK/ElectrumBCHA, started working on the code, and before the first release we Github forked  PiRK/ElectrumBCHA to BitcoinABC/ElectrumABC. So now Github is understandably confused about which should be the direct parent of my personal repository.

But in this instance I'm quite sure that I had selected the correct parent repository, and I guess I didn't wait for the page to refresh accordingly before clicking.

Maybe I should delete PiRK/ElectrumBCHA and fork it again, so that it doesn't happen again. But then I will have to remember to intentionally visit you and say hi, because I will no longer happen accidentally.

**Comment by cculianu** [comment]
Ha ha. 👍 

You can say hi anytime man. I do appreciate you having caught that last bug in the refactor of the `electron-cash` entrypoint script.  Thanks for that.  No worries -- say hi anytime!

**Pull request closed without merging**
