### PR TITLE
NSIS: Create installer log using AdvUninstLog.nsh

### PR DESCRIPTION
**Pull request by EchterAgo**
The installer has a problem with removing its files / directories recursively. This risked users accidentally deleting their wallets if they were stored in the installation directory. To protect against this a check was added to ask the user to confirm the deletion. This in turn broke silent installations because the prompt couldn't be skipped.

To fix this we add `AdvUninstLog.nsh`, which allows the installer to log all the files it is installing and then only delete the files it actually installed when uninstalling. We also add an uninstallation prompt when an existing installation is detected.

The `AdvUninstLog.nsh` file was slightly changed to silence a warning. In the `UNINSTALL.LOG_CLOSE_INSTALL` macro `!undef ID ${__LINE__}` was replaced with `!undef ID`.

This also switches the installer to Unicode, ANSI NSIS builds are now deprecated.

### CODE REVIEW

**Comment by cculianu** [comment]
I don't understand this crazy scripting language they have -- but if you say it works, sounds good. I reviewed it for viruses or whatever. Looks good enough to me.

**Comment by EchterAgo** [comment]
> I don't understand this crazy scripting language they have -- but if you say it works, sounds good. I reviewed it for viruses or whatever. Looks good enough to me.

Yea, that damn scripting language is hard :\

**Comment by EchterAgo** [comment]
https://ec.loping.net/4.2.3-104-g6bd96a30f/

**Comment by EchterAgo** [comment]
@IdealChain this should fix silent install for the chocolatey package.

**Comment by cculianu** [comment]
> > I don't understand this crazy scripting language they have -- but if you say it works, sounds good. I reviewed it for viruses or whatever. Looks good enough to me.
> 
> Yea, that damn scripting language is hard :\

Yeah I believe it's a very old language like from the 1990s that was thrown together quickly for the nullsoft winamp installer.. originally.

**Comment by IdealChain** [comment]
> @IdealChain this should fix silent install for the chocolatey package.

Nice work if it works :smile:

**Pull request merged**
