### PR TITLE
appimage build: bundle dependencies of Qt xcb plugin

### LINKED ISSUE #2263: Electron 4.2.4 fails to run on Debian stable
The new Electron AppImage fails to run on Debian Buster (stable), and, probably on earlier Debian versions:

[code]user@machine:~$ bin/Electron-Cash-4.2.4-x86_64.AppImage 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Abort
user@machine:~$[/code]

After small investigation, it seems highly likely™ that the problem is generated by an absence of libxcb-util.so.1 on Debian Buster and all earlier Debian releases. They have only libxcb-util.so.0

### PR DESCRIPTION
**Pull request by EchterAgo**
We recently bumped the bundled version of PyQt to 5.15.5. It seems the new version has a lot more dynamic dependencies.

From https://doc.qt.io/qt-5/linux-requirements.html :
> From Qt 5.15 onwards, Qt does require libxcb 1.11. Also, the -qt-xcb
> configure option got removed that was bundling some of the libs below.

We are using the prebuilt wheels for PyQt5 from PyPI. Presumably those had previously been built using the -qt-xcb option.

See https://github.com/spesmilo/electrum/issues/7198

https://ec.loping.net/4.2.4-56-g7072f27f2/

closes #2263

### CODE REVIEW

**Comment by EchterAgo** [comment]
@fyookball @cculianu is there any issue with merging this?

**Comment by cculianu** [comment]
Oh sorry -- no issue, I am not sure how we forgot about this.  We actually just prepared a release.  Should we put the release on hold and re-build it with this?

**Comment by EchterAgo** [comment]
I'm not sure how many people this affects, but given that it affects default installs of Debian Stable and Tails, probably many. If we choose to rebuild we should also upgrade the AppImage OpenSSL version, a new one was released to the mirrors:

https://github.com/EchterAgo/Electron-Cash/commit/ab1bd49cfa3d071a0fe7efe785f91d9227f6b642

**Comment by cculianu** [comment]
Ok I'll tell Jonald to put the current release binaries he build on hold, and I'll also cherry-pick your commit off your branch to this one.

Hopefully we can re-tag 4.2.6 and get it out today with these commits. Thanks for the heads-up man.

**Comment by cculianu** [comment]
Ok well after merging this looks like the versions are all out of date, lol. Will fix.

**Pull request merged**
