### PR TITLE
Updated TREZOR plugin to trezorlib-0.11.x

### PR DESCRIPTION
**Pull request by jhoenicke**
Ported spesmilo/electrum@c33c90733008fd8f88a374dfe9098dad9c50b6c9.

### CODE REVIEW

**Comment by cculianu** [comment]
Wow @jhoenicke... thanks for this.

I like a Trezor so I can’t thoroughly test it (just for sanity checking) but I can use the emulator on Linux, right?

I’ll look at this and likely merge it later today when I get home or tomorrow.

Thanks again.

**Comment by cculianu** [comment]
@jhoenicke Can you also add a modification to `contrib/deterministic-build/requirements-hw.txt` to this PR to specify the exact trezor version (==0.11.1 or whatever) for a deterministic build?

Thanks.

**Comment by cculianu** [comment]
@jhoenicke Also, see this recent Electrum commit: https://github.com/spesmilo/electrum/commit/192ec8596d085f9d3dfb9b6a9231ada68ef0fbb8

Is it relevant?  If so, you may want to add what SomberNight did there to this commit as I see it's almost the same code.

Thanks.

**Comment by jhoenicke** [comment]
@cculianu You can build the emulator under linux with docker, see README.md in https://github.com/trezor/trezor-mcu

Running `trezor.elf` under linux should start an empty trezor.  You should run the Trezor bridge with an additional option `trezord -e 21324` so that it detects your Trezor (but I think python-trezor can also access the emulator without the bridge).  You can initialize the Trezor with `trezorctl` or the trezor.io/start web site.  Unfortunately my first test showed that there are still problems initializing the uninitialized Trezor with electroncash; I have to look into this more.

I mainly tested with my existing wallets and an initialized Trezor, there are still problems running recovery with electroncash.

Note that the emulator stores all keys unencrypted in emulator.img, so do not use it with important seeds.

**Comment by cculianu** [comment]
Ok @jhoenicke I will take a little time to try and get the emulator working. I'm in the middle of some other feature addition to electron cash's UI now though.

Do you think this is ready for merging now? Are you happy with it? Let me know and I can merge it without messing with the emulator(and I can do the emulator play stuff later when I get some free time).

What are your thoughts?

**Comment by cculianu** [comment]
If you want me to forever be eternally grateful -- would you have the time to build this on Wine and/or MacOS and just make sure the packaged version works and there are "no surprises"? I don't anticipate any.  Only if you have time and the inclination.

Already you have done a lot for keeping hardware wallets alive and working well in Electron Cash, @jhoenicke .. so as always very much appreciated and thanks!

**Comment by cculianu** [comment]
@jhoenicke ping ping. should I merge it? You happy with it?

**Comment by cculianu** [comment]
@jhoenicke I'll assume your lack of response represents your silent consent that this PR is amazing. Merging to clear out the queue.

**Comment by jhoenicke** [comment]
Hi @cculianu,

sorry for not replying. I was abroad and had no cable to test with real hardware.  But I think it should be good now.  If there is still a problem I'll open a new pull request.

**Comment by cculianu** [comment]
Ah, I see. No worries!

Yeah it seems to be running fine.  After merging I tried to build Mac & Windows and some of the requirements in the Mac and Windows build needed updating (I did that already).  it's all good now!

**Pull request merged**
