### PR TITLE
Anti-Phishing -- Suspicious Server detection.

### PR DESCRIPTION
**Pull request by cculianu**
If it looks like a URL or HTML appears in the server response, then print a critical warning and pop up the network dialog, asking the user to switch servers:

screen shot 2018-12-27 at 8 21 46 pm

If it looks like a name.tld appears in the response, suppress the error message (real server responses never have WORD.WORD).  This way phishers can't pass on any information to users that contain anything that even remotely resembles a URL.

If the error message is otherwise kosher, forward it to the user.

### CODE REVIEW

**Comment by markblundeberg** [comment]
It's may be possible to circumvent this by putting things in using html entities (instead of ., put the hex code). Really we need to at least adopt [HTML escaping](https://docs.python.org/3/library/html.html) or force rich_text to False.

**Comment by imaginaryusername** [comment]
For a hotfix, I'll advocate for simply suppressing all messages - specific suppression of certain types of messages can be circumvented in novel wordings and it'll be difficult to account for all of them.

**Comment by cculianu** [comment]
@markblundeberg  note that HTML is turned off for these popups now. That has been committed to HEAD... so I am not sure about HTML escaping being an issue.

@imaginaryusername Yes, we may just need to do that.  May just shelve this commit for now as someone (was it you) pointed out you can get around it with unicode character magicks. Although if I catch unicode chars I may also consider it a "suspicious response"... ;)

**Comment by cculianu** [comment]
@markblundeberg @imaginaryusername  I just trapped for Unicode errors and made the actual error message be hidden by a "Show Details..." button.  See below screenshot:

Defaults to no details...

screen shot 2018-12-27 at 10 00 55 pm

... And this is the details ...

screen shot 2018-12-27 at 9 57 33 pm

**Comment by imaginaryusername** [comment]
Looks good, for security though removing "details" button altogether might still be better. If we have to show the details, it might be good to word in more agnostically ("Show server return" instead of "Show details") and add a disclaimer on the box "Server returns are potentially useful for troubleshooting, but might be unreliable. If you are unsure about the situation, do not follow server messages."

**Comment by cculianu** [comment]
Ok, @imaginaryusername  -- I did something even more forceful in the reply.

What do you think?

ec_error_message_new

**Comment by imaginaryusername** [comment]
Looks good to me.

**Comment by cculianu** [comment]
Note: While I initially wanted to suppress errors -- they are really useful for troubleshooting problems.

I'm still on the fence about showing any text but -- for right now this might be a sufficient hotfix.

Should I merge this?

@fyookball  @markblundeberg  @imaginaryusername ?

**Comment by markblundeberg** [comment]
Looks good to me. Now, what other parts of Electron Cash involve showing a server-generated error to the user?

**Comment by cculianu** [comment]
@markblundeberg -- Hmm.. good question.  I'll dig around more but so far, as far as I can tell, it's only in this 1 function that other code calls to broadcast_tx's (can't vouch for what plugins do though)..

Guys do let me know if we should suppress them altogether.  This PR is just in case we wanted to keep the server messages...

**Comment by cculianu** [comment]
We merged an alternate PR, #1076 instead of this. Closing.

**Pull request closed without merging**
