### PR TITLE
Build: Add cffi to the requirements

### LINKED ISSUE #2201: DNSSEC error: No module named '_cffi_backend'
I am getting this error message if I try to use OpenAlias:

|337.868| |35| DNSSEC error: No module named '_cffi_backend'

EC cannot verify DNSSEC.

Reproduce:

Start Electron Cash via cmd.exe
Enter an OpenAlias in the Send Tab (try testnet@21.cash or mainnet@21.cash)
OR
Enter an OpenAlias in Tools->Preferences->Fees&Misc

### PR DESCRIPTION
**Pull request by EchterAgo**
When using dnspython for dnssec cffi is required.

closes #2201

### CODE REVIEW

**Comment by EchterAgo** [comment]
https://ec.loping.net/4.2.4-26-g51c8cc6a8/

**Comment by EchterAgo** [comment]
This is a regression caused by the addition of `--no-deps` in e70dcb70428390d37d410a29d8e2568b2ebe9bfe

**Comment by georgengelmann** [comment]
> 
> 
> https://ec.loping.net/4.2.4-26-g51c8cc6a8/

I have tested the portable and installable executables on Windows 10 Home: OpenAlias does not produce an error with this fix.

**Comment by EchterAgo** [comment]
I tested the installable and the AppImage, both successfully resolve OpenAlias without DNSSEC errors now.

**Comment by cculianu** [comment]
Ok, thanks for the fix guys and the trouble-shooting. Looks good to me.

**Pull request merged**
