### PR TITLE
Shorten boolean expression, use double quotes

### PR DESCRIPTION
**Pull request by gasull**
This change is [Reviewable](https://reviewable.io/reviews/electron-cash/electron-cash/2209)

### CODE REVIEW

**Comment by gasull** [comment]
In case it isn't obvious (it wasn't for me), this is why `bool()` around `seed` is needed:

```Python
>>> seed = ""
>>> True and seed
''
>>> seed and True
''
>>> seed = "correct horse battery staple"
>>> seed and True
True
>>> True and seed
'correct horse battery staple'
```

**Comment by cculianu** [comment]
Well, so long as we are being terse -- the parentheses are not necessary either. :)

**Comment by gasull** [comment]
> Well, so long as we are being terse -- the parentheses are not necessary either. :)

True.  Done.

**Comment by cculianu** [comment]
Ok, thanks for the code cleanup.  Looks better.

**Pull request merged**
