### PR TITLE
[WIP] Ledger Nano X Fixes

### LINKED ISSUE #1598: Ledger Nano X feedback
on MacOS Connecting to Ledger Nano X (usb connection) is clunky AF.  Basically, you get this error message after selecting your device and then clicking 'next' until you enter your pin.  Even after entering your pin and being in the proper Bitcoin Cash app this error still appears, until clicking about the 10th time it finally takes.  

image

### PR DESCRIPTION
**Pull request by cculianu**
Hopefully closes #1598 .

This is a work-in-progress for now -- I need to make sure the refactor didn't break anything with the other wallets (it shouldn't, as I read the code -- but I will need to test to make sure).

Will write a better description here when done.

### CODE REVIEW

**Comment by jcramer** [comment]
Works great, no crashes, I think sufficiently address #1598 to close it.  

The only comment I could come up with was it would be nice if the message `'NoneType' object has no attribute 'handler'` displayed sometimes during new wallet creation (when not in Bitcoin Cash app) could be replaced with something more meaningful. Like `"original error'\n\nBitcoin Cash app may still be loading on device, please try again"`. 

It seems like ledger needs a few seconds to load the app or sync the proper device state before it will accept.

**Comment by EchterAgo** [comment]
@jcramer to fix the NoneType message, you need to figure out what error the wallet returns in that case. It should print it to verbose output. When you figure out the error, you need to add it here:

https://github.com/Electron-Cash/Electron-Cash/blob/master/plugins/ledger/ledger.py#L212

**Comment by EchterAgo** [comment]
Tested with Ledger Nano and Ledger Nano S on Windows & Linux.

**Comment by jcramer** [comment]
> It should print it to verbose output

@EchterAgo the error occurs before ledger.py#L212 and checkDevice are called.  I will continue looking at it in the morning.

**Comment by EchterAgo** [comment]
IIRC the error occurs when create_client returns None:

https://github.com/Electron-Cash/Electron-Cash/blob/master/plugins/ledger/ledger.py#L575

Maybe you can trace execution starting from there?

**Comment by cculianu** [comment]
I was unable to reproduce this `NoneType` error. I'll continue to bang at it here.  Let me know how to reproduce it if you can @jcramer

**Comment by cculianu** [comment]
> Tested with Ledger Nano and Ledger Nano S on Windows & Linux.

@EchterAgo thanks for testing. :)

**Comment by cculianu** [comment]
Ok, merging. This closes #1598.

**Pull request merged**
