### PR TITLE
Cash Accounts Implementation + Many Bug Fixes

### LINKED ISSUE #1035: Cash Account Integration
I am currently working on a specification for on-chain aliases that look like this: James#577821; to help convey payment information in a more convenient manner, particulary in verbal contexts.

The specification has undergone reasonable peer-review so far (by wallet developers, token developers, coinbase engineeers) but more feedback is always welcome.

Here's a link to the draft spec: https://gitlab.com/cash-accounts/specification/blob/master/SPECIFICATION.md

### PR DESCRIPTION
**Pull request by cculianu**
Screen Shot 2019-07-08 at 2 02 53 PM

Closes #1035 .

The main UI components to it are in:

- **Contacts tab**
- Addresses tab, right click -> Register new.. (to register to a specific address)
- Tools -> Lookup Cash Account
- Receive tab (to register a cash account on the fly to the receive address there in the tab)

What it has:

- *Full verification* -- users are never presented with any results unless they are first SPV verified. They are also warned when a cash account in the contacts tab is no longer verified (due to reorg?) and won't offer it as an option for pay-to.

- Cash Account Registration Auto-Detection™ - Detects cash accounts related to the wallet (that is, registration tx's for the wallet) whenever it "sees" a tx. This can either be a tx that came through the normal wallet "add_transaction" path or if the user explicitly opens a tx, etc.

- The lookup facility is pretty robust and resilient to all sorts of shenanigans.

What it lacks:

- 100% Send tab niceties: Right now the only way to send to a cash account from the send tab is to **first** add it as a contact in the contacts tab.

This last Send Tab bit is a somewhat complex UI flow but I will do it.  I just wanted to get this PR merged in.

As I was working on this I fixed/found/cleaned up a ton of bugs and made the code tighter overall.

This PR includes all of that as well, so I would like to merge it fairly soon and move forward from master with work on Cash Accounts send tab perfection.

### CODE REVIEW

**Comment by EchterAgo** [comment]
```
068ff6b279298049f9e3900093a6a278bbe390f920ad1866dbee92f2246ddf5d  dist/Electron-Cash-4.0.7-204-g5b21cdbb4.exe
947399b4f20224baa3ec8c64f414b28adf1f00d8ab10410bfc25d29d5dcffc9d  dist/Electron-Cash-4.0.7-204-g5b21cdbb4-portable.exe
bfd65214e8eafb46f5869b1541250e8af518f795a45eeb752ac9153cf5770232  dist/Electron-Cash-4.0.7-204-g5b21cdbb4-setup.exe
75f8c7172bb23bfb88df23ced088d80fcf02c39e1b96eb1d327db6083ec5d6b8  dist/Electron-Cash-4.0.7-204-g5b21cdb-x86_64.AppImage
```

**Comment by EchterAgo** [comment]
http://iris.loping.net/upload/ec/cashacct/

**Comment by cculianu** [comment]
Oh nice @EchterAgo !. I wonder if I should do a macOS build.. hmm 🤔

**Comment by cculianu** [comment]
macOS Build here, same commit: 

https://c3-soft.com/downloads/BitcoinCash/Electron-Cash/testing/Electron-Cash-4.0.7-204-g5b21cdbb4-macosx.dmg

**Comment by emergent-reasons** [comment]
Documenting the things we discussed on telegram:

1. Some linux suckers like me will have black/white emojis even with the AppImage
2. "Mine" contacts don't auto-complete for sending
3. The default wording on the Receive tab (`This address does not have a Cash Account`) may make users nervous about whether they have a problem and need to do something or if it's just normal.

**Comment by EchterAgo** [comment]
From my testing in #1498 the black/white emojis are an issue on Mint 19 & Fedora 29. On CentOS 7 / Ubuntu 16.04.

All of these issues can be resolved with custom fontconfig rules, which we should document somewhere. 

Put this into `~/.config/fontconfig/fonts.conf`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```

and make sure your system has the Noto Color Emoji package installed.

**Comment by EchterAgo** [comment]
Tested and working great on:

* CentOS 7 -> emojis mixed, needs fontconfig adjustments
* Debian 9
* Debian 10 -> schnorr sigil is a box
* Fedora 29 -> multiple emoji fonts, needs fontconfig adjustments
* Mint 19 -> multiple emoji fonts, needs fontconfig adjustments
* Tails 3.13
* Ubuntu 14.04
* Ubuntu 16.04 -> emojis mixed, needs fontconfig adjustments
* Ubuntu 18.04
* Windows 7
* Windows 10 1803
* Windows 10 1903

**Comment by cculianu** [comment]
@emergent-reasons Thanks for documenting the thing we discussed. 

1. We definitely need to document the way to get color using fontconfig. Unfortunately there's no easy way I can think of (but maybe @EchterAgo knows?) of how to detect if the fonts are b/w versus color. Worst case thing I can think of: You can do hacks like render them to a QPaintDevice and sample the pixels and then from that you can "know". :)  So it's possible to actually warn user in-app about their emojis sucking and link them to our docs.  That would probably be best? I dunno. What do you think @EchterAgo ?

2. Yes, I fixed that. Nice catch.  Pushing a commit now to address it. 

3. Yes. I'm fixing now. You're right.. it's.. too ominous.

**Comment by EchterAgo** [comment]
I don't think we need more changes for Linux fonts now. The whole thing is screwed and we at least provide a fallback font. If the users system doesn't have the glyphs or prefers others, that's a configuration issue. I'll work on something to give the user the option to install fontconfig overrides, but I think it's outside of the scope of this pr. We already got emojis on windows 7 now, so I consider this a huge success.

**Comment by cculianu** [comment]
Yeah considering how it looked terrible everywhere (even win10, where it shouldn't have) -- this is a great success already for sure.

**Comment by cculianu** [comment]
Oops. I mistyped. I meant to say that commit fixed #1503. Argh.  Now I have to reopen this PR, ha.

**Comment by cculianu** [comment]
Ok, reopened as #1505. Gah. Sorry!

**Pull request closed without merging**
