### PR TITLE
CashAccounts: Added cashacct.electroncash.dk as a server

### PR DESCRIPTION
**Pull request by atroxes**

### CODE REVIEW

**Comment by cculianu** [comment]
Awesome, thanks! 👍

**Comment by cculianu** [comment]
Hey man I keep getting this error from Python when hitting your server:

```
| 37.926| |22| HTTPSConnectionPool(host='cashacct.electroncash.dk', port=443): Max retries exceeded with url: /lookup/242 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'tlsv1 alert protocol version')],)",),))
```

Oddly enough, it works ok in the browser. :/

Any chance you can see about troubleshooting this?

**Comment by cculianu** [comment]
I did some digging and basically your server is using a bad certificate.  Can you make sure to have a signed certificate for the name `cashacct.electroncash.dk` ?  It's not sufficient to re-use your other cert for electroncash.dk -- it has to be signed for that specific hostname.

**Comment by cculianu** [comment]
Let me know what you plan to do otherwise I will temporarily comment out your server if I don't hear from you in a few days :)

**Comment by atroxes** [comment]
> 
> 
> Let me know what you plan to do otherwise I will temporarily comment out your server if I don't hear from you in a few days :)

It's using a wildcard LE cert, which should be okay. The issue was probably that I only allowed TLSv1.3.

It will accept TLSv1.2 now as well.

**Comment by cculianu** [comment]
Ah! Great! I just tested it and it works flawlessly.  👍 

Yeah I am not exactly sure what this python `requests` library expects but I guess it wants TLSv1.2.

Thanks for responding so quickly, and thanks for running the servers you do.  The more servers, the better.  Much appreciated! :D

**Pull request merged**
