### PR TITLE
Fix Coinbase exchange rate api

### PR DESCRIPTION
**Pull request by imaginaryusername**
Coinbase seems to have changed their api endpoint, adapting.

### CODE REVIEW

**Comment by cculianu** [comment]
Awesome.

**Comment by cculianu** [comment]
Do you know if they have a historical API?  Would be nice to add them to the history rates too..

**Comment by imaginaryusername** [comment]
Doesn't seem like it =\ documentation here: https://developers.coinbase.com/api/v2#exchange-rates

**Comment by cculianu** [comment]
Yeah I just checked.. 👍 

In other news I fixed  bug (with the historical  rates) where if the server was returning a bad status sometimes an empty dict would be in place, which the code did not cope well with because it would save an empty dict to the file as if it were a "good' set of quotes.

So yay!

**Pull request merged**
