### PR TITLE
servers.json: add greedyhog.ddns.net

### PR DESCRIPTION
**Pull request by greedyhog**
Greetings,

I started a server and I plan to maintain it. I would like to offer it to the world!

### CODE REVIEW

**Comment by cculianu** [comment]
Would you mind terribly if we asked you to configure ElectrumX to set MAX_SEND to at least 4MB?

This is the relevant env var:

```
export MAX_SEND=4000000
```

**Comment by imaginaryusername** [comment]
Can confirm server works!

**Comment by greedyhog** [comment]
`MAX_SEND=10000000`

Thank you!

**Comment by cculianu** [comment]
Yeah this allows for users with addresses that have large histories to sync to your server. EatBCH is one such address. If you set it and restarted your server i can test it now.. testing...

**Comment by cculianu** [comment]
Yep. Works good! :D

**Comment by greedyhog** [comment]
Raised the BANDWIDTH_LIMIT as well.

**Comment by cculianu** [comment]
nice! this should allow for larger wallets to have a decent time.  thanks a lot for this.

Also you may want to set a banner file..  This is what I see on EC console connected to your server:

Screen Shot 2019-10-26 at 7 55 56 PM

You can set the ElectronX env var:

```
export BANNER_FILE=banner.txt
```

You can specify an absolute path, or if not, the directory is relative to your `DB_DIRECTORY`.

**Comment by cculianu** [comment]
FYI the banner is just some text. Here's what my banner file looks like:

Screen Shot 2019-10-26 at 7 59 06 PM

It's really only for nerds that use the console.. but at lest it helps identify your server and if you like you can say something about your server such as bitcoind version, etc (you don't have to if you'd rather not reveal too much -- up to you).

**Comment by greedyhog** [comment]
Banner set, thank you!

**Pull request merged**
