### PR TITLE
Console: Escape key exits keyboard focus

### PR DESCRIPTION
**Pull request by EchterAgo**
Without this you can exit the keyboard focus from the console as the Tab key is used for completion.

### CODE REVIEW

**Comment by cculianu** [comment]
Hmm.  For keyboard navigation?

Previously esc. undid the last completion, and that's it.

Now it undoes last completion and also makes you lose focus which is annoying to power users (like me) that use the console a lot.  

I see what you're getting at here -- you want to make it possible to leave the console with just the keyboard.

However that's a rarer cases (which perhaps does need to be handled, granted) -- but for that rarer use case we sacrifice the more common usecase of users hitting ESC and expecting the completions to vanish (as they did before), and that's it.

I am not sure I agree with this change due to the above consideration.

**Comment by EchterAgo** [comment]
Oh, I didn't notice that ESC already has a use. key other than tab closes the completion. So you can just use enter or whatever for that. I can make it so it only exits focus if completion is not open.

**Comment by cculianu** [comment]
I didn't realize any key closed it.. I always instinctively used ESC...  The problem with that... is sometimes you hit esc nervously and you end up unfocused. Hmm.

**Comment by EchterAgo** [comment]
If you unfocus, you can just press tab to get focus again.

**Comment by EchterAgo** [comment]
I made the change so that it requires escape 2 times when completions are visible.

**Comment by cculianu** [comment]
> If you unfocus, you can just press tab to get focus again.

Yes, but it's arguably disconcerting to lose it in the first place if you aren't expecting that.  I'm hitting esc. now a bunch of times in this textbox in my browser and I don't lose focus.  There's no place else for me to go on this page except this textbox.  Same goes for the console tab.

It's too stateful.

I would much rather we add a hotkey combo to change tabs or something if you want users to have a way to "escape" that screen with the keyboard.

It is unexpected to lose focus -- just so you can navigate tabs.. I would argue it's such a rare thing a user would want to do and losing focus on the only obvious widget on a page feels a little frustrating.
 
I get the problem you're trying to solve -- you want a user that lacks a mouse and/or a power user to be able to navigate with the keyboard.  

Perhaps as hotkey combo that does NextTab/PreviousTab would solve the problem you want and be a boon to keyboard users.. without losing focus on that console tab....?

**Comment by EchterAgo** [comment]
> Yes, but it's arguably disconcerting to lose it in the first place if you aren't expecting that. I'm hitting esc. now a bunch of times in this textbox in my browser and I don't lose focus.

ESC to exit keyboard focus from a control that captures keyboard navigation keys is pretty much standard in many places, for me it is much more unexpected to not get focus. The reason why some textboxes don't do that is likely because they do not interrupt keyboard navigation.

> There's no place else for me to go on this page except this textbox. Same goes for the console tab.

You can get to the status bar icons (which have weird tab order btw)

> Perhaps as hotkey combo that does NextTab/PreviousTab would solve the problem you want and be a boon to keyboard users.. without losing focus on that console tab....?

The problem with using another key is that it is not intuitive.

**Comment by cculianu** [comment]
I know.  So on the one hand: ESC is the usual way to escape a control/textfield/etc.

On the other -- can you empathize with the disconcerting feeling when one loses focus in this 1 context?

I'm just not sure.. hmm.

**Comment by EchterAgo** [comment]
I think I have a solution here, only exit focus on Shift+Tab. People who are used to keyboard navigation will just try Shift+Tab when Tab doesn't get them where they want.

**Comment by cculianu** [comment]
That sounds good!

**Comment by EchterAgo** [comment]
Updated so that only Shift+Tab escapes keyboard focus.

**Comment by cculianu** [comment]
Looks good.  I like this one more.  Thanks man.

**Pull request merged**
