### PR TITLE
Remove electrumx-bch.cryptonermal.net server, it runs ABC 0.22

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by epitomeof** [comment]
hello. I can change this. which full node should it run instead?

**Comment by cculianu** [comment]
@epitomeof BCHN, BU are known to work with BCH and to also work with your server software (ElectrumX).

You are currently on the forked ABC coin chain.  If you wish us to not remove you from the hard-coded server please let us know when you complete the upgrade to BCHN or BU.

**Comment by cculianu** [comment]
@epitomeof  Ok here's what to do:

1. Download BitcoinCashNode: https://bitcoincashnode.org
2. Stop ABC, uninstall it but keep the same datadir.
3. Use your same conf file and datadir with BCHN.
4. Once it loads up, you will need to issue some RPC commands to it to get it to see the BCH chain and switch from the ABC chain.  Do:

- `bitcoin-cli -conf=/path/to/your/bitcoin.conf invalidateblock 000000000000000004284c9d8b2c8ff731efeaec6be50729bdc9bd07f910757d`
- `bitcoin-cli -conf=/path/to/your/bitcoin.conf reconsiderblock 0000000000000000029e471c41818d24b8b74c911071c4ef0b4a0509f9b5a8ce`

Verify that you are on BCH chain do:

- `bitcoin-cli -conf=/path/to/your/bitcoin.conf getblockstats 0000000000000000010482ca64d5b9a8df87ec557290fb07bf793e72938a0ab6`

If you get a reply to that last command you are now on the BCH chain again.

ABC went rogue and they forked off to make their own coin.

**Comment by epitomeof** [comment]
lol, crazy.

**Comment by epitomeof** [comment]
okay, done.

**Comment by EchterAgo** [comment]
Seems to be working, your server is on the BCH chain again. Thank you!

**Pull request closed without merging**
