### PR TITLE
Update transaction.py to accept both capitalizations of locktime

### PR DESCRIPTION
**Pull request by The00Dustin**
Fixes https://github.com/Electron-Cash/Electron-Cash/issues/2780

Adjusting "lockTime" case to "locktime" for deserialize to match case for serialize in commands.py as per option (1) of the issue. This case also matches with raw tx output of bchblockexplorer.com and fullstack.cash ElectrumX/Fulcrum API as well as Electrum's commands.py. Additional change for serialize to accept both capitalizations discussed as option (3) in the issue is NOT included in this PR.

The fixed problem is also mentioned in https://github.com/Electron-Cash/Electron-Cash/issues/2775 but this commit does not fix the main problem reported in that issue.

### CODE REVIEW

**Comment by cculianu** [comment]
While I agree that the original capitalization maybe is not ideal, I'm hesitant to accept this change.. it's just an internal variable name. Modifying this core class may affect other plugins, etc.

**Comment by The00Dustin** [comment]
I understand your concern, but deserialize and serialize are incompatible with one another without this change.  This is why I mentioned option (3), which would be non-breaking.  Would you like me to modify this branch that way?

**Comment by cculianu** [comment]
Oh option 3 is to fallback to trying both? Yeah I guess whichever one is there, pick that one. If none are there, use 0....

**Comment by The00Dustin** [comment]
Branch is modified to option 3.  The example from the issue and JSON with 'locktime' both serialize as expected when I run from this source.

**Comment by The00Dustin** [comment]
Or should I close this PR and start a new one?  The name of this one no longer matches the code change...

**Comment by cculianu** [comment]
Ok, looks good to me.

**Pull request merged**
