### PR TITLE
[fusion] include 'distinct coins' concept when enforcing privacy threshold

### PR DESCRIPTION
**Pull request by markblundeberg**
Auto fusion will happily send up to 3 coins from same addr into
a fusion, basically doing a 'free consolidation'. But they shouldn't
count as distinct entities towards our privacy-minimum of 11
inputs+outputs contributed to a fusion.

### CODE REVIEW

**Comment by markblundeberg** [comment]
This is relevant in the context of the recent 'dustings' that we are having. When consolidating dusts with the 'real' coin on same address, fusion is counting them as two distinct coins towards the minimum of 11 inputs+outputs. But they should only count as one effective input for privacy.

**Comment by cculianu** [comment]
Oh yeah this looks good -- I agree with this change.  Heh, probably should have been this way since the beginning. :)  Hindsight is 20/20 I suppose.

**Comment by markblundeberg** [comment]
I'm going to be testing it a bit more, but it's been going well so far with no problems.

**Comment by cculianu** [comment]
The code looks good to me -- I don't see any typos (Darn this python!).. I ran a fusion or two and it works.   If you want to merge it -- go ahead or I can merge it whenever.  Let me know!

**Comment by markblundeberg** [comment]
Yeah I'm happy with this now :+1:

**Comment by cculianu** [comment]
OK, cool. Merging. Thanks for this.

**Comment by cculianu** [comment]
Oops. I did a "Rebase & Merge" thinking that would look like a clean commit.  It has my name on it. :/

I'll just do merge commits in the future or squash -- whatever you prefer.  Sorry about that.

**Pull request merged**
