### PR TITLE
Fix redundant calls to save_addresses during synchronization

### PR DESCRIPTION
**Pull request by mhsmith**
Currently `save_addresses` is called after every address is added. Since this copies the entire address list to storage every time, the cost is n**2 in the number of addresses. For wallets with thousands of addresses, the initial synchronization process was spending more than half of its time in `save_addresses`.

So I've changed it to save the addresses in the same situations as it saves the transactions:
* When synchronization is complete.
* When the wallet is closed.

This reduced the synchronization time of an 11,000-address wallet from 20 minutes to 6.

### CODE REVIEW

**Comment by cculianu** [comment]
This looks great! Nice catch.  It should also help with the desktop version since users of that version tend to have tens of thousands of addresses.  Let me review this in more detail tomorrow and merge it.  Thanks Malcom!

**Comment by cculianu** [comment]
Reviewed, looks great.  In the very unlikely event that the app crashes or is killed and the addresses don't get saved, it's no big deal either.  Presumably the synchronizer will just have to fast-forward again from a previous state.  This commit is pure optimization for the common case with zero drawbacks.  The fact that it saves addresses on `up_to_date` is a nice touch.

Merging!

**Comment by mhsmith** [comment]
> In the very unlikely event that the app crashes or is killed and the addresses don't get saved, it's no big deal either. 

It's a lot more likely on mobile because the user might turn the device off, or the OS might kill the app once it goes to the background. So I'm going to add an auto-save feature to the Android app: I'll write it in Python so you can use it in the iOS app if you want.

**Comment by cculianu** [comment]
Yeah and the “penalty” in that case if it happens it more expensive/more painful on mobile. Good point.

Sure please do share and I will definitely use it. Cool stuff.

Alternatively,  just a dumb heuristic in synchronizer  to “Sometimes” pass save=True there might be enough. Say every 10 or 20 times .. something like that.

**Pull request merged**
