### PR TITLE
Add Bitcoin Unlimited managed Electrum server to the white list

### PR DESCRIPTION
**Pull request by sickpig**
The instance is comprised a BU full node (1.7) and an ElectrsCash
electrum server (1.0) and run on pretty beefy machine we setup to
provide a robust instance.

### CODE REVIEW

**Comment by cculianu** [comment]
Done!

**Comment by cculianu** [comment]
TCP port not working on this server...  shall I delete the TCP port mention in the `servers.json` or will you fix the TCP port? 

(TCP is used for Tor, among other things).

**Comment by sickpig** [comment]
> TCP port not working on this server... shall I delete the TCP port mention in the `servers.json` or will you fix the TCP port?
> 
> (TCP is used for Tor, among other things).

@cculianu the only port accepting connections is 50002/TCP. Port 50001 is bind to localhost where the actual Electrum server is listening for request which are proxied from the external net interface.

Will gladly fix this configuration problem, any link handy?

**Comment by cculianu** [comment]
I'm not sure what you're asking.. hmm.  I connected to the server just fine via SSL on port 50002.  Yet the `servers.json` PR also lists port 50001... which is dead to the world.

So.. either we:

1. Delete the 't' entry in the JSON (not a huge deal -- it doesn't HAVE to have that entry -- it can just appear only when user wants SSL, and disappear form their client when they are in TCP mode).

or...

2. You ... re-enable TCP on the server on port 50001?

Either/or work.  Just to reiterate -- TCP is not required.  Let me know if you just have a temporary misconfiguration or if you plan on not supporting TCP, and we can remove the `t` key in its little mini-dict.

Thanks

**Pull request merged**
