### PR TITLE
Update default servers list

### PR DESCRIPTION
**Pull request by imaginaryusername**
spring cleaning

### CODE REVIEW

**Comment by EchterAgo** [comment]
Why remove `bitcoincash.quangld.com`? The server seems to respond.

**Comment by EchterAgo** [comment]
Maybe you can't connect `bitcoincash.quangld.com` because @quangld changed the SSL cert?

https://github.com/Electron-Cash/Electron-Cash/issues/1327

**Comment by cculianu** [comment]
Quangld is alive but he changed his cert. @imaginaryusername can you please correct this in your PR?

**Comment by imaginaryusername** [comment]
I keep getting [SSL: CERTIFICATE_VERIFY_FAILED], so that's indeed the problem - assumed outdated certificate. Let me check.

**Comment by EchterAgo** [comment]
There are also a few servers on `1209k.com` that are not on the server list that we might want to consider adding:

```
electrumx-bch.cryptonermal.net
bitcoincash.network
bch.rossbennetts.com
electron-server.ninja
```

Both `electrumx-bch.cryptonermal.net` and `bitcoincash.network` had > 99.9% uptime this month.

See https://1209k.com/bitcoin-eye/ele.php?chain=bch

**Comment by EchterAgo** [comment]
`electron-server.ninja` and `bch.rossbennetts.com` point to the same server.

**Comment by imaginaryusername** [comment]
rossbennetts keeps giving me `excessive resource usage` even for a quite modest wallet so I'm a bit hesitant to add that

**Comment by EchterAgo** [comment]
I think `bitcoincash.network` is run by @dagurval

**Comment by cculianu** [comment]
There's still a bunch missing.  What about fulcrum.fountainhead.cash?  That's Jt's server.

**Comment by EchterAgo** [comment]
```
    "fulcrum.fountainhead.cash": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
```

`fulcrum.fountainhead.cash` is in there

**Comment by cculianu** [comment]
@EchterAgo Oh. my bad.  What about `bch2.electroncash.dk`?  You can go to server list in EC and all the servers that aren't starred are good and should probably be added @imaginaryusername

**Comment by imaginaryusername** [comment]
already added that

**Comment by cculianu** [comment]
Ah ok my bad. I really need to check the full file.  The diff I clicked on in github email just showed latest commit. :(

EC only speaks `1.4` -- can you go in and change all the `1.4.x`'s to 1.4?  I am not sure if that breaks things.

**Comment by imaginaryusername** [comment]
I can, but is that necessary? 1.4.x's are kinda indicative of the underlying software at the time of update...

**Comment by cculianu** [comment]
I am 60% sure it breaks things.  Let me check the code -- I remember it breaks things if EC sees a version > what it understands.

**Comment by EchterAgo** [comment]
We already have servers with version > 1.4, so I don't think it will break.

**Comment by cculianu** [comment]
Oh, no. It works. That's fine.  So long as it's >= what EC speaks.

**Comment by cculianu** [comment]
OK, LGTM

**Comment by quangld** [comment]
I am moving away from using quangld.com
So I changed the domain of my server from **bitcoincash.quangld.com** to **bchisbitcoin.com**
Please update if possible, it's not really urgent. Thank

**Comment by cculianu** [comment]
Ok, done.  Tested and verified the server works. Thanks for the heads-up.  I like the new domain name :) 👍

**Pull request merged**
