### PR TITLE
dnssec: fix compat with dnspython 1.16 and 2.0.0

### PR DESCRIPTION
**Pull request by EchterAgo**
`dnspython>=2` breaks our dnssec support because we depend on private functions that aren't in 2.0 anymore

### CODE REVIEW

**Comment by EchterAgo** [comment]
This is from https://github.com/spesmilo/electrum/commit/6d2aee18d0bc5b68bff4123855f2b77b7efa1f3b

I tested it using my OpenAlias.

**Comment by EchterAgo** [comment]
Added another commit that makes version 2.0.0 work without doing the monkey patching.

**Comment by EchterAgo** [comment]
https://travis-ci.org/github/EchterAgo/Electron-Cash/builds/714357117

**Comment by cculianu** [comment]
Looks great. Thanks for this fix.

**Pull request merged**
