### PR TITLE
Dockerfiles update for git version

### PR DESCRIPTION
**Pull request by markblundeberg**
Not sure if you want to merge these now or wait for next release, but here they are.

### CODE REVIEW

**Comment by cculianu** [comment]
Oh yeah I noticed Electrum did this recently. Did you test these?  Should I just merge?

**Comment by cculianu** [comment]
Looks good to me.  I didn't test it -- but I presume it's now broken. If it breaks (again) we'll know at build time.  Thanks for the update.

**Comment by markblundeberg** [comment]
Yeah it was necessary update for building fusion.

**Comment by cculianu** [comment]
Yeah I figured.  Wish there was a way to better handle this .. oh well.  Thanks.

**Pull request merged**
