### PR TITLE
Adds electrum.bitcoincash.org Electrum server to Electrum server list.

### PR DESCRIPTION
**Pull request by SKlayer**

### CODE REVIEW

**Comment by imaginaryusername** [comment]
bitcoincash.org has been controlled by a party hostile to BCH for a while, who controls it now?

**Comment by cculianu** [comment]
@SKlayer This server is not on BCH, but on taxchain.  We already have it in our server list for taxcoin (`servers_taxcjoin.json`). Can be accessed in the UI with `--taxcoin` CLI arg.

Closing.

**Comment by EchterAgo** [comment]
@cculianu that is wrong, the server is on the BCH chain.

**Comment by EchterAgo** [comment]
Yea, I agree. @SKlayer if you want your server to be used, you can set it to announce itself to the network using the `hostname` setting in the configuration file. The server will get into server lists and EC can connect to it by default. The EC internal server list is intended for known trusted servers.

**Comment by SKlayer** [comment]
> @SKlayer This server is not on BCH, but on taxchain. We already have it in our server list for taxcoin (`servers_taxchoin.json`). Can be accessed in the UI with `--taxcoin` CLI arg.
> 
> Closing.

NO, now they are already switch to bch main now,.

**Comment by imaginaryusername** [comment]
I think most of us need to be convinced that the owners of the domain is someone at least non-hostile to BCH, else it seems imprudent to list a server as default with the full knowledge that they are unfriendly to the chain and its users.

**Comment by EchterAgo** [comment]
@SKlayer If money changed hands for the transfer of bitcoincash.org, you should try to get a refund. The domains reputation is ruined.

**Pull request closed without merging**
