### PR TITLE
Network dialog: Fix not showing .onions before switching to the Proxy tab

### PR DESCRIPTION
**Pull request by EchterAgo**
The state of the "Use tor" checkbox is used to determine whether to show .onion servers in the server list. This used to not be saved and only initialized when switching to the proxy tab, causing .onion server to not be shown.

This patch changes it so that the state of the checkbox is saved. It also removes the proxy_settings_changed code that resets the box to unchecked when the dialog opens. When the user chose to use tor, we disable the ability to change the settings instead.

### CODE REVIEW

**Comment by cculianu** [comment]
The thing is why leave the "Use Proxy" stuff grayed out?  You can end up in this state with no way to recover except to exit Electron Cash.


Screen Shot 2020-01-04 at 9 07 05 AM

**Comment by cculianu** [comment]
I like what you did to make the checkbox sticky.. but.. 

After exiting Tor -- I end up in this state.. no way to specify any other proxy ever again.  The thing is Tor and "general proxy" shouldn't be mutually exclusive like that.  The way I see it.. Tor is a specific kind of proxy -- but the more general proxy should not be disabled forever just because you made the unforgivable mistake of choosing Tor once...  :)

Screen Shot 2020-01-04 at 9 08 44 AM

**Comment by EchterAgo** [comment]
@cculianu this should now be working correctly.

**Comment by cculianu** [comment]
This looks good.  I like that it fixed that glitch.  That glitch was annoying for sure.

I'll merge this now...

**Pull request merged**
