### PR TITLE
Zbar: Update to git master to fix build with autoconf 2.70

### PR DESCRIPTION
**Pull request by EchterAgo**
See https://github.com/mchehab/zbar/issues/132

This needs `autopoint` to be installed.

### CODE REVIEW

**Comment by EchterAgo** [comment]
https://ec.loping.net/4.2.3-84-g97db54e40/

**Comment by cculianu** [comment]
Let me test this on macos too..

**Comment by EchterAgo** [comment]
It needs gettext for autopoint: https://github.com/mchehab/zbar/commit/996dbdb72b90c24c338fa75a59c2e911aba85d44

**Comment by cculianu** [comment]
Tested on macos too. Works here on my MacPorts system.  Merging.

**Pull request merged**
