### PR TITLE
Move to new data and cache directories for Linux and macOS

### PR DESCRIPTION
**Pull request by alexander255**
Follow-up for #641.

Progress:

* [X] Data migration for Linux
* [X] Qt GUI migration notification:  
    Screenshot Qt GUI popup after migration
* [X] Kivy GUI migration notification:  
    Screenshot Kivy GUI popup after migration
* [x] Data migration for macOS ([related code](https://github.com/fyookball/electrum/pull/641#issuecomment-398731072))
* [x] Seperate out the cache directory

### CODE REVIEW

**Comment by rt121212121** [comment]
Looks good to me.  So no-one was using that `translate(*args, **kwargs)` method?  I'd ask if you searched and changed those, but I am assuming they'd have errored?.

**Comment by cculianu** [comment]
Hey Alexander,

I want to help you add/test that code for finding the MacOS Application Support dir.  Probably your user_dir and old_user_dir functions would need to be modified to support it, in addition to that code being pasted in.

Unfortunately, my Macbook Pro died earlier this week.  It's in the shop now and I expect to receive it and have it working by perhaps Thursday of this coming week.

So -- everyone.  *Can we hold off merging until then*?

Thanks!

PS: in the meantime -- Alexander... feel free to try and add the macos-specific code in the appropriate places, if you can.  If not, I can help you with it when my laptop is resuscitated in a few days...

**Comment by alexander255** [comment]
@rt121212121: Apparently so. If anyone had been using it, then it would have worked fine before, except for (possibly non-fatally) crashing when switching the OS language.

@cculianu: Before adding your code I think we need to discuss this statement you made a while ago:

> When the app is "running form source", it'll use the Python interpreter's bundle identifier: org.python.python.
> 
> However, when it's the final dist .app file complete with its own "Info.plist" that we ship out, it will be "Electron-Cash" (this is wrong and should really be org.electroncash.Electron-Cash -- but c'est la vie -- the devs that did this initially didn't 'get' macs :) ).
> 
> So we may want to hard-code the bundle identifier in our python sources as always being 'Electron-Cash' as is in the shipped app so that users running from source don't find their wallets missing suddenly and vice-versa. :)

If we cannot rely on the bundle ID being reported correctly by the OS when users run the app from source, then we'll have to hard-code the app ID anyways, no? So should I just hard-code `os.path.join(application_support_dir, "org.electroncash.ElectronCash")`?
The only other way I see this could be achieved is by scanning `contrib/build-osx/osx.spec` for the current bundle ID if the OS reports it as `org.python.python`. I somewhat like this option more because it makes things a bit easier for forks, but it results in a bit more code.
It's your call here basically.

**Comment by cculianu** [comment]
Hey Alex,

You're right.  Man you're good.  :)

I agree with the simplest thing (I'm all about whatever works lately) -- join the path with the hardcoded string org.electroncash.ElectronCash.  While you're doing that change -- would you mind modifying osx.spec to switch from bundle id  "Electron-Cash' (which is wrong) to you better formed org.electroncash.ElectronCash (just for symmetry's sake)?

BTW: I'm still on my windows desktop -- I expect my laptop to be ready tomorrow or Thursday at the latest.... I can add all that code myself then.

Actually something occurred to me -- that function I gave you depends on the standard python lib 'ctypes' so perhaps also setup.py or whatever thing specifies the dependencies (osx.spec?) needs to be updated to include ctypes as a module dependency for Electron Cash.  ctypes itself is tiny as a lib so it shouldn't affect the footprint of electron cash much.

**Comment by rt121212121** [comment]
Pretty sure ctypes is in stdlib.

**Comment by alexander255** [comment]
@cculianu: I've pushed both the bundle change and the macOS directory discovery code. The code is inspired by your sample code but was rewritten to be a lot more readable and maintainable. Could you please test it when you have your laptop working again? I have no idea if it'll work, and there's likely at least one dumb mistake somewhere in there. :upside_down_face:

**Comment by cculianu** [comment]
Hi Alex,

I got my laptop today and got it working late in the day! Yay!

I like that you refactored it into a separate file!  Perhaps more stuff that's macOS specific can go in there.

Right now I tested it briefly and the file has 1 syntax error (you forgot to import the c_ssize_t type which you use later).

After fixing that missing symbol, I noticed that it gave me garbage values when called:

(I did this from the interactive interpreter):

```
>>>> get_bundle_identifier()
'\x00\x00\x00\x00'
>>>> get_user_directory('application-support')
PosixPath('\x00\x00\x00\x00')
```

So I'm assuming there's some encode/decode issue.  I can fix that for you tomorrow.  I'll send you a patch here or perhaps pull request to your repo tomorrow for this.

Now -- 1 other thing -- I noticed the file uses 'tabs' instead of '4 spaces'.  Since the rest of the project is set to use 4-spaces for indents -- can you go back and make sure all your stuff is using 4 spaces?

Reason being .. well, consistency!

Anyway I'll fix this file's not working either later tonight or tomorrow.. expect a pull request from me on your fork or somesuch..

**Comment by cculianu** [comment]
Update: I actually created a pull request on top of your forked repo suggesting changes to the util_macos.py file.  More explanation given in the PR itself. :)

It at least works now -- but you may not like my "dumbing it down" with respect to the ctypes stuff. ;)

**Comment by alexander255** [comment]
Hi everybody! I know I took a break from this for a while, but hopefully it was for the better :slightly_smiling_face: 

Anyways, thanks to @cculianu's help and and the final patch I just added this should now work on all major desktop platforms using the correct path in each case. When migrating the data directory a dialog is shown using both Qt and Kivy afterwards (see OP); changing the cache directory happens silently on-the-other-hand.

The new directories are (summary):

  * Windows:
     * Data: `%APPDATA%\ElectronCash` (as before)
     * Cache: `%LOCALAPPDATA%\ElectronCash`
  * Linux:
     * Data: `${XDG_DATA_HOME:-${HOME}/.local/share}/electron-cash`
     * Cache: `${XDG_CACHE_HOME:-${HOME}/.cache}/electron-cash`
  * macOS:
     * Data: `<NSApplicationSupportDirectory>/org.electroncash.ElectronCash`
     * Cache: `<NSCachesDirectory>/org.electroncash.ElectronCash`

Any testing, feedback & review would be greatly appreachiated now!

**Comment by cculianu** [comment]
Hey looks good.  The mac stuff is working as intended.  I'm a little nervous we aren't doing the 100% kosher thing in converting CFString to utf8 c-string (it's theoretically possible for the number of bytes needed to represent the string to exceed the length of the string as returned by CFStringGetLength).

The real way to do it is to call CFStringGetBytes() twice (once with a NULL buffer to get the byte count needed, a second time with a real buffer to get the actual bytes) as described in these docs: https://developer.apple.com/documentation/corefoundation/1543006-cfstringgetbytes?language=objc

I apologize -- I'm the one that initially suggested we do the CFStringGetCString() way.  But I realize for Chinese characters this may fail spectacularly if the username of a user uses chinese characters.

What should we do?  Shall I submit a PR to your repository Alexander to address this?

Again -- my bad and I'm sorry... :)

**Comment by alexander255** [comment]
> @cculianu: What should we do? Shall I submit a PR to your repository Alexander to address this?

Yes please. No problem for submitting another PR. I'm glad somebody tests this on macOS. :slightly_smiling_face:

**Comment by cculianu** [comment]
Ok, PR submitted. 

Also, you're welcome for the macOS tests.  I'm a macOS fan and use it as my primary OS so.. it helps me too!

**Comment by cculianu** [comment]
Hey, this looks good -- FYI this is what it looks like on macoS:

screen shot 2018-08-15 at 8 05 09 pm

I'm still waiting for the ok from Jonald Fyookball because I think he had some reservations about changing this now and perhaps he wanted us to wait.

So be patient!

**Comment by marceloneil** [comment]
Would it be possible to place something into the old directory like a file named `DIRECTORY-MOVED` or some sort of indication along those lines?

**Comment by alexander255** [comment]
@marceloneil: Absolutely! Do you wish for me to add that?

**Comment by alexander255** [comment]
Today I just tested EC again and found somewhat grave issue after migration: The wallet save file paths are still pointing at the old location in the configuration. After removing the old `~/.electron-cash` directory the wallet would then appear to be “gone” and the default wallet would be loaded (no risk of data since the wallets *were* copied, but still surprising behaviour). I've opted to fix this by only storing relative paths for all wallet file whose directory is inside the EC data directory directory and only use absolute paths otherwise. This should also make it easier to copy EC configurations between machines.

After quickly reviewing this issue I also remembered your request @marceloneil and added code that attempts to create a `– FILES HAVE MOVED –` (or `– FILES HAVE MOVED –.txt` on Windows) file in the original directory after the migration is successful. Note however that this will not work if the migration is done by the Flatpak, as I mount `~/.electron-cash` read-only there.

I also saw you @-mentioning in the other thread! I'm investigating a “solution” for this currently. :wink:

**Comment by cculianu** [comment]
PS: For some reason this PR is missing https://github.com/alexander255/electron-cash/commit/321583e1d4b8570a5568a128ed9050f058fd2fda -- this was utf8 issues in util_macos that I caught and fixed.  I am not sure what happened to that commit.  You merged it but it's not in your repository right now.  Maybe you did some force push and clobbered it?

**Comment by alexander255** [comment]
@cculianu: Thanks for noticing the missing commit! I probably never pull it down before adding the other commits on top and rebasing onto latest master, so it likely got lost in some force-push.

My description about the issue I fixed yesterday probably wasn't that good, tbh. I'll try again: The `config` file within Electron-Cash's data directory stores the most recently used wallet path as an *absolute file system path*. Unfortunately this means that, if the data directory and the wallets within are moved the paths stored in the config file become outdated/invalid:

* With the current data migration the old wallet paths will continue to be valid, but will point at the old wallet paths → very bad.
* When running within Flatpak Electron-Cash will start showing random critical errors because the path of the old wallet is now read-only → also bad.
* When the old directory is removed, Electron-Cash will load the default wallet on startup → Unexpected behaviour, especially when the default wallet is empty → very bad.

**Comment by cculianu** [comment]
Oh yeah I noticed that "recently open" wallet code is a bit wonky.  I don't like how it doesn't check that the wallet files actually EXIST when building the menu. If you delete a wallet it still shows up in the menu.

A recent commit of mine addressed this.

I'll look at your PR again tomorrow and try and make sure it doesn't break anything -- it's quite invasive so I really have to be careful here.

Thanks for the more thorough explanation..

**Comment by alexander255** [comment]
@cculianu: Have you made up your mind yet?

**Comment by alexander255** [comment]
@cculianu: Thanks for the status update! I could provide a patch for each branch in parallel – the only real difference should be in the extra parameter of `WalletStorage` (ie: `storage = WalletStorage(path, base_path=self.config.path)`) – but I see how this would likely result in chaos nonetheless if not carefully orchestrated. Ping me when you're ready, I guess. :slightly_smiling_face:

**Comment by cculianu** [comment]
Well, I asked people about it and it was met with resistance basically because everybody already feels like there's too much chaos. 

If you can convince everybody to do it -- go for it.  :)

**Comment by cculianu** [comment]
Hey @alexander255 -- sorry we never merged this.  There was resistance to this in the project... so we decided against this.

*HOWEVER* -- we basically took the very excellent ctypes code you wrote for MacOS (with my help, heh) and added it to another PR where we needed to call into MacOS for stuff like reading default language of the OS.

I want to thank you for the very high quality code you submitted and apologize for leaving you hanging for the better part of a year.

The code quality is very high in this PR.  I'm closing this now, but the PR #1477 contains your macos_utils code, and you will be attributed in the change log.

Thanks and sorry!

**Pull request closed without merging**
