### PR TITLE
Fix user agent incorrectly reporting old electrum agent string

### PR DESCRIPTION
**Pull request by unusualbob**
Noticed it's still sending the old user agent

### CODE REVIEW

**Comment by cculianu** [comment]
Ha! I can't believe this went unnoticed for so long.  Anyone object to merging it? It won't break anything, right?

**Comment by fyookball** [comment]
@cculianu we noticed it before. we just had other priorities :)

**Comment by cculianu** [comment]
Of course Jonald.  I know the weight of SLP is on your shoulders in recent months.  Good job man! Didn't mean to imply anything but respect! :)

This begs the question -- does Electrum X expect a particular user agent (I should hope not).

I'll check out the electrumX sources and if it looks ok, I'll merge this.

**Comment by kyuupichan** [comment]
Lol. You guys.

**Comment by cculianu** [comment]
ok, merged.

**Pull request merged**
