### PR TITLE
Addresses tab: hide all empty change addrs, not just used ones

### PR DESCRIPTION
**Pull request by markblundeberg**
Also, pop open the (now shorter) change address list by default, and fix a bug.

### CODE REVIEW

**Comment by markblundeberg** [comment]
Before & After, though I'm curious how this looks on a wallet that has done heavy shuffling. Is the pop-open by default still a good idea then?

Screenshot_2019-10-09_17-43-45
Screenshot_2019-10-09_17-44-09

**Comment by cculianu** [comment]
Regarding the `is_empty` check... as my jewish friends back growing up would say: "oy vey". LOL. Nice catch.

 Did you also check `lib/commands.py`?  It also calls it but I *think* it actually called it the way you have it now.

**Comment by cculianu** [comment]
Ah so all empties go in the "Empty" list.  I can live with this. 👍

**Comment by cculianu** [comment]
As for the pop open by default.. yeah I think it's a good idea.

Although bizarrely it pops open even if it's just empty, as so:

Screen Shot 2019-10-10 at 9 17 26 AM

Whereas before it wouldn't:

Screen Shot 2019-10-10 at 9 18 27 AM


---

But I can live with that...

**Comment by cculianu** [comment]
Oh i see it's because it's always popped up by default -- which is fine because it's always hopefully going to either be short or have meaningful stuff in it.

I actually like the new behavior a lot.  I'm tempted to merge this right away but please check `lib/commands.py` -- or I can check it in a bit.  It *looks* like actually that code assumed `is_empty` works the way you have it now (which is illustrative of how poorly the function was previously named).... but I can't be sure.

Hell .. I'll check it and merge.

This PR: Nice change actually.

**Comment by cculianu** [comment]
Ok, can confirm. `commands.py` assumed your fixed behavior. "Oy vey!". :)

**Comment by cculianu** [comment]
Oops. I swear I picked "squash and merge". Sorry!  At least we get more commits out of the deal.. :)

**Comment by markblundeberg** [comment]
Haha no worries

**Comment by markblundeberg** [comment]
The funny part about the bug is that Neil helpfully inserted a second bug to compensate. :joy:

**Comment by cculianu** [comment]
Any opportunity to disparage our real enemy, Neil, is always welcome. Let me check git blame... where?

**Comment by markblundeberg** [comment]
Same commit!

**Comment by markblundeberg** [comment]
( 919e1b9)

**Comment by cculianu** [comment]
Right that's where he broke it. Then like 1 or 2 commits later "Fix thinko".. he "compensated" for it by modifying `is_used()` to use the inverted version..

Grrr..

Luckily this wasn't called much by anything...

**Pull request merged**
