### PR TITLE
ElectrumX server electroncash.ueo.ch will be shutdown in the near future

### PR DESCRIPTION
**Pull request by torusJKL**

### CODE REVIEW

**Comment by cculianu** [comment]
Are you the server operator?

**Comment by cculianu** [comment]
(I ask only because we have had a round of sybil attacks going on lately and a good servers.json file is our only defense right now...)

**Comment by cculianu** [comment]
Ok, got confirmation it's him off reddit. Merging.

**Comment by torusJKL** [comment]
Thanks for merging and the work you are doing.

**Pull request merged**
