### PR TITLE
Ledger: Add Nano-S-Plus USB device ids

### PR DESCRIPTION
**Pull request by vrabe**
I tested a little, and it works for me.
relates to #2417

### CODE REVIEW

**Comment by cculianu** [comment]
Unable to test as I lack those devices. I believe you that it works.  Merging!

**Comment by tjulien-ledger** [comment]
Hi @cculianu , @vrabe , We are still facing some issues with the nano S plus and Electron-cash. Can you please have a look? The device is not detected when attempting to import wallet using a Nano S plus and the BCH app.

**Comment by tjulien-ledger** [comment]
Thank you for your reply @vrabe :) I tested with the latest version of electron so 4.2.10 as for the nano I am using a nano S firmware 1.0.3 with latest version of the Bitcoin and Bitcoin Cash apps so 2.0.6.

**Comment by vrabe** [comment]
@tjulien-ledger This pr has not released yet. So you need to wait the next version released or build the master branch yourself.

**Comment by EchterAgo** [comment]
I have an automatic build for Windows and Linux that includes this change:

https://ec.loping.net/4.2.10-11-g870daefa8/

The binaries are signed with this key:

https://github.com/Electron-Cash/Electron-Cash/blob/master/pubkeys/axelkey.txt

**Pull request merged**
