### PR TITLE
AppImage: Make build reproducible

### PR DESCRIPTION
**Pull request by EchterAgo**
We build our own mksquashfs from squashfskit which supports generating reproducible squashfs images. We use a small wrapper script to remove the -mkfs-fixed-time which appimagekit passes but squashfskits mksquashfs does not support.

### CODE REVIEW

**Comment by cculianu** [comment]
This is awesome. Thanks.

**Comment by EchterAgo** [comment]
Building with
`GIT_REPO=https://github.com/EchterAgo/Electron-Cash ./contrib/build-linux/appimage/build.sh appimage_reproducible`

is a reproducible build producing this hash:

`94708be7b208f0e2c6256240e3eebe718e729c9717913561a20f427ab5f1e5be  dist/Electron-Cash-4.0.7-dev2-2-g360a77f-x86_64.AppImage`

**Comment by EchterAgo** [comment]
There is still an issue with reproducible builds on a Linux host. The libpython binary we generate sometimes does not pick up the faketime timestamp:

image

Most of the time it works and produces the correct binary, but sometimes it doesn't. Feels like ~25% chance to generate the wrong binary to me (this might be off a lot). It also does not happen on macOS it seems. There are some weird messages that I sometimes get more or less of during build that might be related:

```
💬 34mINFO:  Building Python
make: Warning: File `Makefile' has modification time 0.16 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.4 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.55 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.69 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.83 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.051 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.26 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.52 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.69 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.11 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.29 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.56 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.7 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.88 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.074 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.27 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.52 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.68 s in the future
The Makefile was updated, you may need to re-run make.
make: Warning: File `Makefile' has modification time 0.94 s in the future
Objects/obmalloc.c:1212:1: warning: ‘no_sanitize_thread’ attribute directive ignored [-Wattributes]
```

**Comment by EchterAgo** [comment]
I think this is ready for merging, it is reproducible, just not 100% reliable. The python thing seems to be a separate bug.

**Comment by cculianu** [comment]
I suspect sometimes the Python build system is "too smart" and libfaketime doesn't succeed at intercepting the system calls.  This would not be a problem if Python actually supported `SOURCE_DATE_EPOCH`. We may have to resort to using this patch here: https://github.com/python/cpython/pull/5313/files and apply it to the downloaded python sources.

Strange that it only picks it up 25% of the time.  And we make with `-j4`.  Coincidence? :)

This may even just be a docker bug, actually.  The fact that on macOS docker it's 100% reproducible is a sign...

Anyway will merge.

**Pull request merged**
