### PR TITLE
build: update dependencies

### PR DESCRIPTION
**Pull request by EchterAgo**
There are some security changes in these, OpenSSL and zbar have security fixes, I think the zbar one is critical.

### CODE REVIEW

**Comment by EchterAgo** [comment]
https://github.com/EchterAgo/Electron-Cash/actions/runs/8005836403

**Comment by EchterAgo** [comment]
I think there is still an issue with the Windows build, for some reason it failed to find openssl.

**Comment by EchterAgo** [comment]
seems to be the libevent change

**Comment by cculianu** [comment]
macOS builds same as before and runs same as before. Merging.

**Comment by EchterAgo** [comment]
https://github.com/libevent/libevent/issues/1136

**Comment by EchterAgo** [comment]
should work this time: https://github.com/EchterAgo/Electron-Cash/actions/runs/8006480028

I removed the `libevent` upgrade, it is not critical for us. I'll submit another PR once I figured out how to make it link to OpenSSL.

**Comment by cculianu** [comment]
Ok, lmk when ready then.

**Comment by EchterAgo** [comment]
@cculianu it is ready, I tested Windows and AppImage. Tor works.

**Comment by EchterAgo** [comment]
Hmm, I just tried to install a plugin and it crashed. This seems to be unrelated to this though

**Pull request merged**
