### PR TITLE
Add historical BCH/USD exchange rates from CoinCap

### PR DESCRIPTION
**Pull request by jonas-lundqvist**

### CODE REVIEW

**Comment by cculianu** [comment]
Ha ha! I love you man.  I didn't think you'd actually do it (so quickly)!  Uh-- want to join our slackk and hang out with the "cool kids"? (Are you in our slack)?

**Comment by jonas-lundqvist** [comment]
@cculianu Sure, where and how do I find your slack?

**Comment by cculianu** [comment]
I am not sure if I have to invite you.  Maybe you can email me your email address and I can invite you by email?  `calin _dot_ culianu "AT" gmail.com`

👍

**Comment by cculianu** [comment]
Nevermind.  I invited you to your email address listed on your website. :)

**Pull request merged**
