### PR TITLE
Network dialog: Change to some better looking icons

### PR DESCRIPTION
**Pull request by EchterAgo**

### CODE REVIEW

**Comment by cculianu** [comment]
On macOS these look far superior. Let my try Windows 7 real quick to make sure it doesn't explode...

if not we should merge this.  It looks a lot better.

**Comment by EchterAgo** [comment]
On Windows 10 they also look much better. I'll check AppImage.

**Comment by cculianu** [comment]
Windows 7 looks great too.

**Comment by EchterAgo** [comment]
Updated to fix a small bug in make_emojis and include the new symbols in our supplemental font. It now looks great in AppImage as well. I think we can merge this.

**Comment by EchterAgo** [comment]
Ooops, sorry, haven't pushed yet.

**Comment by EchterAgo** [comment]
Updated

**Pull request merged**
