### PR TITLE
update default server list

### PR DESCRIPTION
**Pull request by markblundeberg**
This updates `lib/server.json`, the initial seed list. This list includes 9 servers that will fork off onto the new ABC rules (three BU, six ABC), and 2 servers that will fork off onto the new SV rules. Was generated using `scripts/servers` then modified. Note that the 'version' field has been incremented from 1.1 to 1.4 since all these servers support protocol 1.4.

Many servers were omitted:

* Servers running old node versions (XT 0.11, ABC 0.17, BU 1.3/1.4), not ready for Nov 15 fork day.
* Servers running BU 1.5 / ABC 0.18 with unpatched ElectrumX (they will crash on Nov 15).
* Servers with expired certs.

Survey for reference:
https://docs.google.com/spreadsheets/d/1xFthIiIG1lUBczGwUinazBzjRinuRmCi9h_xfUSAjZM/edit

(plz don't merge yet)

### CODE REVIEW

**Comment by cculianu** [comment]
Awesome.  Just let me know when it's ready to merge!  

👍

**Comment by kyuupichan** [comment]
Seems quite a biased choice...  Why not let it be until post-fork?  Given that

a) the servers check each other and only report those following their chain, and will all be reporting each other until at least several hours after the fork
b) servers currently running old software still have 15 days to change
c) the client software selects the server with the longest chain unless the user explicitly overrides (so old servers would not be part of the choices)

I don't really see the point in this, other than removing servers that have been down for an extended period.

**Comment by wisbwond** [comment]
@markblundeberg  I'm running electrum from @kyuupichan. Do I have to update to https://github.com/Electron-Cash/electrumx in order to support the fork?

**Comment by markblundeberg** [comment]
@kyuupichan Ah interesting, I wasn't aware of all those details. Hmm... if so, perhaps the best plan of action is to just add as many servers as are running right now, to top it up. I've already pruned off dead ones in a previous PR and the seed list is getting a bit small (effectively only six of the servers on the current list can be accessed by wallets right now).

@wisbwond depends, if you are running ABC 0.18.2 for example then Neil's ElectrumX will crash. If SV, then no change needed.

**Comment by kyuupichan** [comment]
Sure; seems wise to have 10-12, that is a mixture, and that have been around for a while

**Comment by kyuupichan** [comment]
You'll all be switching back to ElectrumX anyway  😂

Luckily for those following the ABC chain, I fixed ElectrumX (hopefully) to handle the reorg back to the SV chain.  The SV daemon will not be able to serve the blocks on the ABC side that you'll be needing to back up, so you would normally be stuck rebuilding your DB from Genesis...

**Comment by markblundeberg** [comment]
Changed to have 19 servers, which seem to all be active these days.

**Comment by cculianu** [comment]
Ok, merging.

**Comment by protonn** [comment]
Please add 
35.157.238.5
t: 51001
S: 51002

**Pull request merged**
