### PR TITLE
Network dialog: Add tor icon to node list as well

### PR DESCRIPTION
**Pull request by EchterAgo**
Same as in the server list.

### CODE REVIEW

**Comment by EchterAgo** [comment]
I have no good idea how I can test the chain split specific code of this. Any idea?

**Comment by cculianu** [comment]
> I have no good idea how I can test the chain split specific code of this. Any idea?

Testnet has an active chain split going on if you make sure that your client sees that `electrum-testnet.criptolayer` server as one of its 10 connected servers.. (it is on some stuck testnet I think):

Screen Shot 2020-01-04 at 10 09 41 AM

To make sure your client "sees" it.. you can explicitly connect to it once and switch away then it should remain active as one of the lucky 10...

**Comment by cculianu** [comment]
This looks great -- I love that little onion.  Makes me kind of want to eat onions... Is this ready for merge?  this code doesn't really look like it depends on the chain fork code.. does it?


Screen Shot 2020-01-04 at 10 12 34 AM

**Comment by cculianu** [comment]
It seems to look on on fork too:

Screen Shot 2020-01-04 at 10 14 23 AM

**Pull request merged**
