### PR TITLE
Ledger: Fix warning about unverified inputs

### PR DESCRIPTION
**Pull request by EchterAgo**
Starting in version 1.4.0 of the Ledger Bitcoin app, additional data needs to be sent for inputs to prevent the firmware warning about unverified inputs. See https://donjon.ledger.com/lsb/010/

### CODE REVIEW

**Comment by EchterAgo** [comment]
I tested this with a Ledger Nano S. I tested P2SH multisig and P2PKH.

**Comment by EchterAgo** [comment]
Oh, I also tested multiple outputs in one transaction.

**Comment by EchterAgo** [comment]
I want to test this with HW1, so don't merge this yet.

**Comment by EchterAgo** [comment]
Updated to work on HW1. Also removed misleading comment, the `witness` flag is not needed for CashAddr, it is needed for BIP143 sighash.

This is now tested with a Ledger Nano S and a Ledger HW1 with P2SH and P2PKH.

**Comment by cculianu** [comment]
Awesome.. looks good to me.  Thanks for addressing this!

**Pull request merged**
