### PR TITLE
Add instructions to compile the icons for Qt

### PR DESCRIPTION
**Pull request by georgengelmann**
I tried to run Electron Cash from source on Ubuntu 20.04 and 18.04.6 and it did not create the icons automatically

This command fixes the error:

"Cannot open file ':icons/electron-cash.svg', because: No such file or directory"

### CODE REVIEW

**Comment by cculianu** [comment]
Isn't icons.py already in the source tree?  I don't get it.

Unless you ran from the tarball and not a git checkout?

**Comment by fyookball** [comment]
@cculianu Indeed, which is why we removed those instructions a while back.  But for some reason, icons were not showing up in his ENV (and rebuilding fixed it).  Perhaps because it was a virtual machine.  I suggested we add those instructions back in, in case anyone needs to resolve issues of the resource file not being able to read, which is apparently possible.

**Comment by cculianu** [comment]
Maybe mention that "may need to do this if you get icon errors"?  IDK.  If not just feel free to merge this...

**Comment by georgengelmann** [comment]
Maybe I was doing something wrong. I just followed the instructions and tried it on 22.04.1 and the icons are working in VirtualBox.

However I have noticed that you need **python3-requests** instead of **python-requests**

and **python3-distutils-extra** to build the translations - that's not mentioned in the README.rst

**Comment by fyookball** [comment]
Yeah I think its good to add it in the readme just in case , but we should say something like "normally you can skip this step"

**Pull request merged**
