### PR TITLE
Windows: Make console work properly

### PR DESCRIPTION
**Pull request by EchterAgo**
This patch adds console functionality for the Windows build. As the Windows .exe is a Windows subsystem executable it doesn't have a console. We solve this by checking if there is a console of a parent process that we can attach to.
Additionally the --forceconsole parameter can be passed to force allocating a new console if no parent console is found.

### CODE REVIEW

**Comment by cculianu** [comment]
This is awesome. So just to summarize:

- `--forceconsole` is checked before the args are even parsed and ripped out of sys.argv -- this is so the console can appear as early as possible in the program's execution

- `--forceconsole` just always creates a separate window even if there is a parent with a console.

- `--forceconsole` should perhaps imply `-v`.

- We discussed this in slack: I don't think `-v` should imply `--forceconsole` because.. well. if they run with -v they probably already are on the command-line. No?

**Comment by EchterAgo** [comment]
1. Yes
2. It did previously, right now it only does when it can't attach to a console. What do you think is the best behavior here?
3. I'm not really sure if there even is much usable console output without -v
4. Yea, when using -v it is likely started from command line already
5. You should use ordered lists when you want to discuss a list of things

**Comment by cculianu** [comment]
(2) I think what you have now is the best behavior, tbh.

(3) Yes. I agree. there is practically 0 output without -v.  So maybe -v should imply force. Easy check is have your force flag at the beginning scan for -v and `--verbose` as well in `sys.argv`

(4) Right.. unless they created a special `.lnk` file by hand in which case they can figure it out if they're that smart. :)

(5) Gotcha.

**Comment by cculianu** [comment]
At any rate I'm going to the gym and will merge this when I get back unless you tell me to wait. Thanks again!

**Comment by EchterAgo** [comment]
3. Ok, I'll make it check for `-v` and `--verbose` and not remove them from `argv` if found.

**Comment by cculianu** [comment]
Here for posterity:

- Related issue: https://github.com/spesmilo/electrum/issues/2592

**Comment by cculianu** [comment]
Actually just having the `-v`/`--verbose` check should be enough.  You may not even need the `--forceconsole`.. it may be superfluous.

**Comment by EchterAgo** [comment]
Yea, I removed that.

**Comment by cculianu** [comment]
Ok. Perfect. Merging now.

**Comment by EchterAgo** [comment]
Oh, I wasn't done testing the last push. I'm pretty confident it will work though.

**Comment by cculianu** [comment]
Ha ha ha. :)

Let me know if it doesn't!!!

**Comment by EchterAgo** [comment]
It is working fine.

**Comment by fyookball** [comment]
FYI this refers to actual windows console, not the console tab in EC.

**Comment by cculianu** [comment]
@fyookball yep. thanks for clarifying that for the casual reader.

**Comment by turcol** [comment]
This may help you to run your electrum in console mode, without changing your code
https://github.com/spesmilo/electrum/issues/2592#issuecomment-484562196

**Comment by cculianu** [comment]
@turcol thanks for this.. we already changed the code to "do the right thing" since.. you know.. doing the right thing is the right thing to do. :)

**Comment by cculianu** [comment]
Note to anyone reading this that wants to re-use this PR.  This PR had a slight bug with respect to MSYS/Cygwin terminals.  Addressed in this commit:  45f29b6ab4ca5582f4d645ce687ffe7086e4afbc

**Pull request merged**
