### PR TITLE
QR Scanner -- Massive rewrite and revamp

### PR DESCRIPTION
**Pull request by cculianu**
After much trial and tribulation by mostly Axel Gembe (@EchterAgo) -- it is ready!

The new Electron Cash QR Scanner!

qr_finder_ss

Pros:

- Uses Qt to talk to the camera -- as a result most cameras are supported
- Same UI on all 3 platforms (macOS, Linux, Windows)
- Should in theory work with any platform (provided user has libzbar installed)

Cons:

- None that I can think of.  

Notes:

- 100% Cross-platform Camera support -- no more awkwardness.  It uses QtMultimedia to read from the Camera (most of the processing is done natively in Qt and not by Python).
- The camera's image frames are sent to either `libzbar` on Windows & Linux, or a custom `.dylib` I wrote for macOS -- both native libs -- for fast & accurate detection.
- Our Linux & Windows build/packaging scripts have been updated to build zbar, package it, and include it.  We include the latest zbar sourcecode from the new maintainer -- it should cope much better with hard-to-decipher QRs, etc.

Most of this work was Axel Gembe (@EchterAgo) with work from me as well -- but he did the heavy lifting here!  Thanks Axel!

### CODE REVIEW

**Comment by EchterAgo** [comment]
Tested on latest Arch & CentOS 7

**Comment by EchterAgo** [comment]
Tested on Debian 9

**Comment by EchterAgo** [comment]
Tested on Mint 19

**Comment by EchterAgo** [comment]
Tested on Fedora 29

**Comment by EchterAgo** [comment]
Ubuntu 14.04 fails but can be fixed by installing an updated gstreamer PPA:

https://forum.qt.io/topic/77275/unable-to-execute-the-player-example-after-a-fresh-install/9

```
sudo add-apt-repository ppa:dan-witt/gstreamer
sudo apt-get update
sudo apt-get upgrade
```

**Comment by imaginaryusername** [comment]
Works on Fedora 30/KDE. 

Slight nit: This is the send box in 4.0.3: 
Screenshot_20190524_010952

This is the send box in githead and this PR: 
Screenshot_20190524_010747

The change is subtle but kind of bothers me in an uncomfortable way. Any chance of making it look more like 4.0.3 again?

**Comment by cculianu** [comment]
- Tested as "srcdist" on Ubuntu 18.04 as well as AppImage Ubuntu 18.04
- Tested on Windows 7 and Windows 10 (build .exe's)
- Tested on macOS El Capitan, High Sierra, and Mojave

**Comment by cculianu** [comment]
@EchterAgo that's fine as a workaround. The odd user running Ubuntu 14.04 can be told to update the gstreamer ppa.  There's no easy way to solve that. We're good as far as I'm concerned.  The fact that it works on Debian 9 is huge, as well as all the weird CentOS's and others.

@imaginaryusername hmm.. we did update that code recently to align the buttons better.. can't have everything!!  I am inclined to just "leave it be" -- we slaved over that PayToEdit a lot recently to get it to play nice on all platforms with all themes (dark, light, custom, etc) (you'd be surprised how hard that was!) .

If it makes you feel better that PayToEdit is "Special" in that it's a multiline edit really.. you can hit enter and create more lines.. so that extra space is now a hint of that! :P

**Comment by EchterAgo** [comment]
Tested on Tails 3.13.2

**Comment by EchterAgo** [comment]
Tested on Windows 10

**Comment by cculianu** [comment]
I am merging now.. 3.. 2... 1..

**Pull request merged**
