### PR TITLE
add missing opcode names

### PR DESCRIPTION
**Pull request by markblundeberg**
I tried to invoke OpCodes.OP_CHECKLOCKTIMEVERIFY and surprisingly after all this time, it wasn't there. Here are added four opcode names (I'm including checkdatasig too).

### CODE REVIEW

**Comment by rt121212121** [comment]
It remains to be seen if these opcodes will exist, I am against partisan changes like this unless it is done in a way compatible with either the ABC co-fork or the SV fork.

**Comment by markblundeberg** [comment]
Yes, the first two should hopefully be non-controversial (as they're on all bitcoins now), but I understand about OP_CDS.

(It shouldn't cause any compatibility issues btw, as these are just labels on numbers. The opcodes list does already include other things that are invalid right now like [OP_VERNOTIF, OP_MUL, etc.](https://en.bitcoin.it/wiki/Script#Opcodes))

**Comment by markblundeberg** [comment]
I've updated it to remove CDS for now, but also to include NOPs [based on spesmilo repo](https://github.com/spesmilo/electrum/blob/master/electrum/transaction.py).

**Comment by markblundeberg** [comment]
(I have also removed OP_SINGLEBYTE_END which hasn't existed for ages, see [earlier](https://github.com/fyookball/electrum/issues/828))

**Comment by rt121212121** [comment]
Thanks Mark, we need to work out how we're going to proceed with a non-partisan way forward so both eventualities can be supported.  We should bring this up on slack general channel and without discussing politics or personal opinion of each fork, work out a way to support both.

**Comment by markblundeberg** [comment]
Any opposition to this? The current diff only puts in opcode names that exist on all forks.

**Comment by cculianu** [comment]
I'm perfectly OK with this, since it doesn't pick a side thus won't upset anyone. Merging.

**Pull request merged**
