### PR TITLE
[macOS] Add QR Scanner with no external dependencies

### PR DESCRIPTION
**Pull request by cculianu**
---

me_ec_test

---

This feature adds much-needed QR scanning capability to Electron Cash on macOS.

Note that zbar does **not** work on macOS for reading from the webcam.  So -- a different approach was needed.

I did some digging and most other approaches I could find have external dependencies that just make building and packaging too cumbersome.  (See: https://github.com/spesmilo/electrum/pull/3485 for an example of a cumbersome approach).

However -- macOS since 10.7 comes with very good video processing capabilities right in the OS.  This includes the ability to decode QR codes! Why bundle heavy-handed libs when the OS already provides them? (And -- they are **hardware accelerated**, to boot!).

So -- I wrote a small helper app that Electron Cash calls.  The entire app is 80KB compiled -- so it's tiny and on the order of the size of other bundled binaries we include on macOS such as `libusb.dylib`. 

The workflow for this app is identical to the 'zbar' approach used on Linux and Windows.

This PR takes care of bundling the helper app in the built .app for macOS.  It also works in "running from source" mode.

The app basically creates a window and reads from the default camera device on the system. It will continue to run until either the window is closed by the user or a QR image is read.

#### Rationale for using a Helper App rather than a dylib

1. macOS Mojave and above require special Info.plist keys and annoying permissions from the user to access the camera. It was far simpler to do this as a self-contained app in "sandbox" mode than to make Electron-Cash.app comply with this insanity.
2. It's far simpler to maintain a standalone app than to build a dylib when it comes to creating GUI windows -- no interference with Electron Cash's event loop. Everything is self-contained.

#### Workflow for the helper app is as follows (note this is identical to zbar):

1. If a QR image is scanned, it will print the decoded string to stdout and exit.
2. If there is an error detecting the camera, it will show an error message and wait.
3. If the user closes the window without having scanned a QR code (because of an error or s/he changed his/her mind), it will print nothing to stdout and exit.

As such, `lib/qrscanner.py` was modified to call the helper app using `subprocess.Popen` in the 'darwin' case. The 'windows' and 'linux' cases were left unmodified.

### CODE REVIEW

**Comment by markblundeberg** [comment]
This PR does involve committing a binary to the source tree, which seems to violate the whole 'deterministic build' process. That said, Calin is our only Mac builder it seems so it is somewhat of a moot point.

Still I think it could be nice to have this PR made in a way that Electrum could adopt it too, as apparently they have a similar issue of lacking QR scanner in Mac.

* Could it be made so that the Mac build process also builds the QR binary from source -- deterministic? I'm not familiar enough with ObjC compilers to know whether this is feasible.
* Can the QR binary be published somewhere so that it gets downloaded as part of build, with verified checksum (like happens with Zbar).

**Comment by cculianu** [comment]
You think the Electrum guys would be against it?

I'm not even entirely certain our builds on macOS are deterministic anymore even with this change. Nor am I convinced they are deterministic for Electrum (we use the same process).

I'd have to double-check that.  At the very end of the build process someone has too sign Electron-Cash.app with their developer key.  We actually have an "Electron Cash" account on mac (as well as on iOS)... so that might be possible to be reproducible by us "trusted devs" but not by the general public..

> - Could it be made so that the Mac build process also builds the QR binary from source -- deterministic? I'm not familiar enough with ObjC compilers to know whether this is feasible.

It could be -- but the problem is macOS app signing.  The app won't run on many macOS's out there if not signed with a developer certificate (basically a public/private key pair) issued by Apple.  Does that violate determinism if only 3 people on Earth can deterministically do it?

> Can the QR binary be published somewhere so that it gets downloaded as part of build, with verified checksum (like happens with Zbar).

What -- the Electron-Cash source repository isn't enough?!

**Comment by SomberNight** [comment]
Nice work.

> I'm not even entirely certain our builds on macOS are deterministic anymore even with this change. Nor am I convinced they are deterministic for Electrum (we use the same process).

We were trying (mainly @bauerj) to make it reproducible for a relatively long time, but it did not work out.

Not sure if we will merge this, but it's definitely something to consider. Could you give some pointers how to build the qr scanner binary? Assume high-level google-fu but non-existent Mac knowledge :D

**Comment by cculianu** [comment]
> Not sure if we will merge this, but it's definitely something to consider. Could you give some pointers how to build the qr scanner binary? Assume high-level google-fu but non-existent Mac knowledge :D

Hey ghost!  Was going to ask you what you think!  As of right now the steps would be:

1. Load included source code in Xcode.
2. Hit build.

But -- that's not exactly scriptable. Luckily command-line tool called `xcodebuild` that is essentially a 'make-like' utility that can grok Xcode `.proj` files and just spit out an app.  Then you have to run this second app called `codesign` to sign it.

So it would roughly be:

1. Chdir to sources
2. `xcodebuild`
3. `codesign -s MY_DEVELOPER_CERT /path/to/built/APPNAME.app`

Very roughly speaking.

**Comment by cculianu** [comment]
I think I'm going to go ahead and merge this. Speak now or forever hold your peace!

I admit it does mean we have a binary in the source tree.  

#### Advantages of this
1. Mac users and devs (like me -- I dev on Mac) can just 'run from source' and it 'just works'. When developer testing I often wished we had a QR scanner.. and now we do!
2. The built app I'm including is signed with a dev key so it will 'just work' on every mac out there in the released .app we send out to users.

#### Disadvantages of this
1. Build is not deteministic.

#### Potential future work-arounds for determinism
1. Get a developer key from Apple
2. Make the `contrib/build-osx` scripts use `xcodebuild` to build the included sources.


I elected *not* to take the above path because it means developer testing (running from source) would  not work until the helper app is built.

Am I evil? Perhaps.  Hate me if you wish.  I am what I am. 👍

**Pull request merged**
