### PR TITLE
Build: Update Python to version 3.8.7

### PR DESCRIPTION
**Pull request by EchterAgo**
The old Python version 3.6 was not getting binary updates for Windows anymore, so updating is needed.

The Linux reproducible buildinfo patch has been updated from Ubuntu.

Python does not have the `--with-threads` option anymore, so that has been removed.

Dependencies have been updated and the `pyscard` install step on Windows has been removed.

`pyblake2` and `websocket-client` unused dependencies have been removed.

The `requirements-build-wine` dependencies have been included in the `freeze_packages` scripts.

### CODE REVIEW

**Comment by EchterAgo** [comment]
Oh, I also included some additional Qt components in the AppImage cleanup.

**Comment by EchterAgo** [comment]
https://ec.loping.net/4.2.3-120-g922a42b12/

**Comment by EchterAgo** [comment]
This is what I found in the PyInstaller build:

```
+cryptography
-google
+_asyncio.pyd
+_cffi_backend.cp38-win32.pyd
+_overlapped.pyd
+_queue.pyd
+d3dcompiler_47.dll
+libcrypto-1_1.dll
+libEGL.dll
+libffi-7.dll
+libssl-1_1.dll
+MSVCP140_1.dll
+opengl32sw.dll
-pyblake2.cp36-win32.pyd
+ssleay32.dll
```

+ are additions compared to 4.2.3, - are removed. Cryptography did not end up in the output before, but it should be there. Not sure about the google protobuf missing, I'm testing this now. Then there are some new python modules. CFFI ends up in the binary even though it should not be needed. PyInstaller places the Qt GL/D3D libs in the root now. Pyblake2 was removed, unused.

**Comment by EchterAgo** [comment]
The protobuf stuff seems to not be needed at runtime. The following succeeds in the console and fusion seems to work:

```
from electroncash_plugins.fusion import fusion_pb2
from electroncash import paymentrequest_pb2
```

**Comment by EchterAgo** [comment]
So, protobuf binaries are not included because there is no wheel built for Windows Python 3.8. It still works because it uses the Python implementation instead of the C++ implementation.

**Comment by EchterAgo** [comment]
I'm going to try to remove the `cffi` dependency, AFAICT only `Cryptodome` uses it and it will fall back to `ctypes` when optimized anyway.

**Comment by EchterAgo** [comment]
In the AppImage, the following libraries were added removed:

```
+libblkid.so.1
+libbsd.so.0
+libgssapi_krb5.so.2
+libk5crypto.so.3
+libkrb5.so.3
+libkrb5support.so.0
+liblz4.so.1
+libmount.so.1
-libz.so.1
```

This is the AppImage builder detecting new Qt dependencies and pulling in more system libraries. In the Python site-packages, this changed:

```
-construct
+cryptography
-websocket
-pbkdf2.py
-pyblake2.cpython-36m-x86_64-linux-gnu.so
```

Cryptography was missing, and websocket / pyblake2 has been removed. I'll have to check `construct` and `pbkdf2`.

**Comment by EchterAgo** [comment]
`pbkdf2` is unused.

**Comment by EchterAgo** [comment]
Trezor is using `construct`, I'll need to add that.

**Comment by EchterAgo** [comment]
Updated to address issues.

**Comment by EchterAgo** [comment]
sha256sums from my desktop:

```
e29e4cae6bffef061fe4cde79eb407cd2d58c6a65427f9bb0b8db54d6887e348  Electron-Cash-4.2.3-120-ge70dcb704.exe
8f4d7986ec51afdd9e497a8cade8a809221d45796957d9bf58c6b04ff089e520  Electron-Cash-4.2.3-120-ge70dcb704-portable.exe
b0613a792c5c073c294fb96486945b287b02d34c7a70ba3bdea3e93c112933fc  Electron-Cash-4.2.3-120-ge70dcb704-setup.exe
edd7085f9f3adb4d14b48c15509ee77fb3273e1bc8bf485cfbfbd9fda5d70603  Electron-Cash-4.2.3-120-ge70dcb704-x86_64.AppImage
```

**Comment by EchterAgo** [comment]
https://ec.loping.net/4.2.3-120-ge70dcb704/

Build server sha256sums match.

**Comment by cculianu** [comment]
> So, protobuf binaries are not included because there is no wheel built for Windows Python 3.8. It still works because it uses the Python implementation instead of the C++ implementation.

This is fine. We actually force the python implementation anyway at runtime because the C++ implementation is kind of buggy for us (it doesn't respect python namespaces properly and can throw errors unexpectedly as a result).

**Comment by cculianu** [comment]
Sorry it took me so long. Excellent work.

**Comment by mhsmith** [comment]
Why did you remove the code in freeze_packages.sh which excluded pip from the output? I'm pretty sure we don't need it at runtime, and it adds [1.4 MB](https://pypi.org/project/pip/20.0.2/#files) to the size of the mobile apps.

**Comment by mhsmith** [comment]
See #1567.

**Comment by EchterAgo** [comment]
@mhsmith We should have the hashes for pip to ensure it hasn't been tampered with. Maybe it should be in a different file though. If you don't need pip at runtime, just uninstall it. I added `requirements-build-uninstall.txt` for packages that can be uninstalled after the build:

https://github.com/Electron-Cash/Electron-Cash/blob/master/contrib/requirements/requirements-build-uninstall.txt
https://github.com/Electron-Cash/Electron-Cash/blob/master/contrib/build-linux/appimage/_build.sh#L116

**Comment by EchterAgo** [comment]
Oh, btw, there are some more Python things we don't need need at runtime that AppImage cleans, you might want to look at this:

https://github.com/Electron-Cash/Electron-Cash/blob/master/contrib/build-linux/appimage/_build.sh#L178

**Comment by mhsmith** [comment]
OK, thanks. Unfortunately the Android build system can't run arbitrary pip commands, so I'll probably just pre-process the requirements file to remove the unneeded packages.

**Pull request merged**
