### PR TITLE
Fetch Input data for TX's (Amount, Address, etc) -- for the Transaction Dialog, asynchronously

### PR DESCRIPTION
**Pull request by cculianu**
Note this works pretty well. I am even caching the results and looking in wallet first.

~~TODO: Perhaps load balance this across connected servers.  For now it really works rather well.~~

Edit: It now hits all servers if enabled.

It's default OFF.  

chkbox - Edited - Edited (2)

### CODE REVIEW

**Comment by markblundeberg** [comment]
me likey

**Comment by cculianu** [comment]
Really? I felt bad I didn't do the button + check thing but.. I just want it to be a tiny compact little control.. I'm glad you approve man.

**Comment by cculianu** [comment]
I tested the hell out of this in all possible cases:

- Online vs offline wallet mode
- Bad vs good connections
- All sorts of wallet setups
- Partials, foreign tx's, weird tx's not on blockchain, with weird prevouts not on blockchain
- Bad/malicious responses from server (simulated)
- Pathological tx histories (each input having a separate tx it comes from, with each of those tx's being close to the limit) (simulated test)

The overall memory consumption is pretty low for the internal cache of tx's it keeps -- ~20 MB even in heavy use -- with a theoretical limit of 100MB for the most pathological cases possible.

I'm pretty happy with this and have spent 2 full days refining and reviewing it.  I'm merging it -- so that I may focus my attention on the other PR's that Mark is working on.  I believe this feature to be crucial and critical for quality -- and will come in handy for the refactoring Mark is doing as well.

**Comment by markblundeberg** [comment]
Haha didn't realize squash-merge made such ugly commit messages! 6112fe0e51e48e9ceaaecf47a014e6f4a7b41703

**Comment by cculianu** [comment]
Yeah I didn't notice it -- I just squashed.  Sorry if it's an eye-sore! I could have just cleaned it up into something more helpful. ha ha ha

**Pull request merged**
