### PR TITLE
Android fixes

### PR DESCRIPTION
**Pull request by mhsmith**
@cculianu: The workaround of making the `locale` directory a Python package is no longer needed in the current version of Chaquopy, so I've restored the previous way of finding it. Does that look alright to you?

### CODE REVIEW

**Comment by mhsmith** [comment]
@cculianu: The workaround of making the `locale` directory a Python package is no longer needed in the current version of Chaquopy, so I've restored the previous way of finding it. Does that look alright to you?

**Comment by cculianu** [comment]
That looks fine but I guess we need to remove it from the PyInstaller spec files in `contrib/build-wine`, `contrib/build-linux`, `contrib/osx` and possibly from `setup.py`.

Feel free to merge this and I can test if it breaks/broke after and fix it then, however.

Thanks for the heads-up.

**Comment by mhsmith** [comment]
Thanks, I've removed `locale` from setup.py. I don't think it needs to be removed from the other places, because they just refer to it as a source of data files, not as a Python package.

**Comment by cculianu** [comment]
Ah ok, perfect. Thanks for looking into it. 👍

**Pull request merged**
