### PR TITLE
Got rid of `imp` rewriting of lib, plugins, and gui dirs

### PR DESCRIPTION
**Pull request by cculianu**
Module `imp` is deprecated and will be removed in a future Python
version. So, rather than do the `imp` rewriting of the lib, gui, and
plugins directories, we renamed these directories to electroncash,
electroncash_gui, and electroncash_plugins to match the Python module
names.

All setup and packaging files have been updated such that Windows,
Linux AppImage, OSX, iOS and srcdist now build correctly using these new
directories.

Android has not been properly migrated over yet, but that will be coming
soon.

~~Also in this commit: updated Dockerfiles for Wine and Linux AppImage
builds since they grew stale and some package versions needed updating.~~

We also bumped the app version to 4.2.0 since this filesystem renaming
change can potentially be considedered a significant enough change, as
per semantic versioning.

### CODE REVIEW

**Comment by cculianu** [comment]
@mhsmith or perhaps @jonas-lundqvist or @mpatc -- I wasn't able to correctly update the gradle file(s) -- and I think the Android version no longer builds correctly.  Would you mind taking this branch out for a spin and getting the Android version to build correctly and then letting me know what I need to change?

@EchterAgo -- If you also have time and don't mind looking over this PR (I know it's large but most of it is renames) -- just to see if I missed anything.  I built AppImage, Windows, OSX, and srcdist and they all work and are correct.

**Comment by EchterAgo** [comment]
A few more changes:

https://github.com/EchterAgo/Electron-Cash/commit/156e95e638e390b02b73976d1d075ca9cc951342

**Comment by EchterAgo** [comment]
Windows & Linux builds: https://ec.loping.net/4.1.1-32-ge4f688765/

**Comment by cculianu** [comment]
> A few more changes:
> 
> [EchterAgo@156e95e](https://github.com/EchterAgo/Electron-Cash/commit/156e95e638e390b02b73976d1d075ca9cc951342)

Argh sorry I should have done a pull off your branch not a cherry-pick.  Can you accept my apology? It was late...

**Comment by cculianu** [comment]
@EchterAgo Ok so my AppImage has a differeent sha256sum than yours.  The Windows EXE's do match, however.

Here is my sha256sum:

```
fb44981d2b6ee294baea51cf1f9f9cc767c5ed74e940140989d869e96a688023  Electron-Cash-4.1.1-32-ge4f688765-x86_64.AppImage
```

I noticed that my build log differs from yours in that I got some warnings (looks like something went awry with the CLI args on one of the commands??):

```
Successfully installed Electron-Cash-4.2.0
You are using pip version 18.1, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Uninstalling Cython-0.29.7:
  Successfully uninstalled Cython-0.29.7
💬 INFO:  Copying desktop integration
💬 INFO:  Adding launcher
💬 INFO:  Finalizing AppDir
ldd: ./usr/lib/python3.6/site-packages/electroncash_plugins/fusion/Cash: No such file or directory
ldd: ./Fusion: No such file or directory
ldd: ./Logo: No such file or directory
ldd: unrecognized option `-'
Try `ldd --help' for more information.
ldd: ./No: No such file or directory
ldd: ./Text: No such file or directory
ldd: ./Gray.svg: No such file or directory
ldd: ./usr/lib/python3.6/site-packages/electroncash_plugins/fusion/Cash: No such file or directory
ldd: ./Fusion: No such file or directory
ldd: ./Logo: No such file or directory
ldd: unrecognized option `-'
Try `ldd --help' for more information.
ldd: ./No: No such file or directory
ldd: ./Text.svg: No such file or directory
ldd: ./usr/lib/python3.6/site-packages/setuptools/command/launcher: No such file or directory
ldd: ./manifest.xml: No such file or directory
ldd: ./usr/lib/python3.6/site-packages/setuptools/script: No such file or directory
ldd: ./(dev).tmpl: No such file or directory
--- errors end above.. everything below proceeds as normal ---
/lib -> ./lib
/lib/x86_64-linux-gnu -> ./lib/x86_64-linux-gnu
'/lib/x86_64-linux-gnu/libc.so.6' -> './lib/x86_64-linux-gnu/libc.so.6'
--- everything below this line is normal ---
```

Any thoughts?  Note I am building on a macOS host using Docker.

**Comment by EchterAgo** [comment]
Doesn't matter, I thought you were going to squash this anyway.

**Review by mhsmith — COMMENTED** [review]
I assume the Android build problem was this one?

> Execution failed for task ':app:mergeMainNetDebugPythonSources'.
>Encountered duplicate path "electroncash_gui/__init__.py" during copy operation configured with DuplicatesStrategy.FAIL

I'll have a look and push a fix to this branch.

**Comment by cculianu** [comment]
Rebased after migrating the Dockerfile fixes over to master.

**Comment by cculianu** [comment]
> I assume the Android build problem was this one?
> 
> ```
> Execution failed for task ':app:mergeMainNetDebugPythonSources'.
> > Encountered duplicate path "electroncash_gui/__init__.py" during copy operation configured with DuplicatesStrategy.FAIL
> ```
> 
> I'll have a look and push a fix to this branch.

@mhsmith 

Yes -- and I think it's because now there are 2 copies of `electroncash_plugins` and `electroncash_gui`.. so maybe rename one or .. something?  No idea.  I guess you copied them over so that generate-strings works...

Thanks man! (Note I just rebased and force-pushed in order to make the Dockerfile fixes for Wine and Linux live in master.. sorry about that!)

**Comment by cculianu** [comment]
Regarding the non-reproducibility for `AppImage` -- @EchterAgo and I traced it down to a bug or quirk in MacOS docker -- it is not related to this PR -- it happens off master too.  That can be investigated separetely.

**Comment by mhsmith** [comment]
The Android build works fine now.

**Comment by cculianu** [comment]
> The Android build works fine now.

Awesome. I'm a little confused -- does this mean it ends up copying all of that code from `electroncash_gui` and `electroncash_plugins` ?

**Comment by mhsmith** [comment]
No, because I've changed the include lines to be more specific. It'll only copy the `__init__.py` files so the directory is recognized as a package.

**Comment by cculianu** [comment]
Ah, ok great @mhsmith  -- thanks a lot for your rapid help here.  Awesome. I'm merging this...

**Pull request merged**
