### PR TITLE
Icons: Use recreated clock icons by the Simple Ledger devs

### PR DESCRIPTION
**Pull request by EchterAgo**
The clock icons were the last icons still stuck with low resolution. We wanted to keep the original look instead of going with a flat look like Electrum but the original vector files seem to have been lost. We decided to recreate the icon so that it closely matches the original when rendered at a low resoltion while giving more detail when rendered at a higher resolution.

The Qt SVG engine seems to have an issue with these SVGs, rendering them somewhat too dark. Until we can figure out a fix for this problem we rasterize the icons.

### CODE REVIEW

**Comment by EchterAgo** [comment]
Don't merge this yet. I'd like to wait until we get updated icons.

**Comment by cculianu** [comment]
Does `clocks.zip` need to be in the repo? Doesn't it just contain the `clockX.svg` files that are already put in the repo by this PR?  I presume you accidentally added it -- if so, can you remove please?

This looks great. Bummer about Qt having weird SVG glitches.  With any luck maybe the new icons won't have any glitches. 

Understood about not merging yet. Thanks for this BTW  👍

**Comment by cculianu** [comment]
May I merge this NAO?  I check it -- they look correct/accurate/good

**Comment by EchterAgo** [comment]
Yea

**Comment by cculianu** [comment]
I'll wait for your final decision on 64 addition and 96 removal..

**Pull request merged**
