### PR TITLE
Scan the current screen for QR code

### PR DESCRIPTION
**Pull request by jonas-lundqvist**
Add an option in the 'Pay to' context menu to scan the current screen
for a QR code.

If someone knows how to easily convey that action as a 16x16
black-and-white icon that someone should probably do an icon for it.

### CODE REVIEW

**Comment by EchterAgo** [comment]
This should also be accessible through the icons on the right side. I'd suggest popping up a context menu when clicking the QR code icon allowing you to select getting the code from either the camera or the screen.

**Comment by EchterAgo** [comment]
Tested on Windows and it is working. Not supporting multi monitor though.

**Comment by cculianu** [comment]
Tested on MacOS too -- works as advertised.  Nice job!

Now.. the load from image never works for me here.  But.. not related to this PR.  Just a lament.

**Comment by PiRK** [comment]
> Not supporting multi monitor though.

I stole your commit so you can have mine, if you are interested: https://github.com/Bitcoin-ABC/ElectrumABC/pull/43/commits/ce4fb2bf13a03c02cae94880e66b960d4720037a

Note that I did not test it with a single screen setup.

**Comment by cculianu** [comment]
Thanks @PiRK and @jonas-lundqvist .. we merged the latest that can do all the screens..

**Pull request merged**
