### PR TITLE
Add support for Satochip hardware wallet v0.12

### PR DESCRIPTION
**Pull request by cculianu**
This is a rebase-and-squash of PR #2402 .  It removes the changes to the submodules and to the language files in that PR.
The original author is: `Toporin <satochip.wallet@gmail.com>`, and he was given credit as such.

Author's message follows:

---

A new version (v0.12) of the Satochip card firmware has been released.
This PR aims to update the Satochip plugin to support the new features
added in v0.12
[(see applet release for more details)](https://github.com/Toporin/SatochipApplet/releases/tag/v0.12):

* (new) Card label
* (improvement) 2FA can be disabled using reset2FAKey() without resetting
                the seed
* (improvement) Reset to factory support
                (using the [FactoryResetTool](https://github.com/Toporin/FactoryResetTool) application)
* (new) Support for personalisation PKI: allows to verify card authenticity
                 based on a device certificate & PKI

Main changes:
* Use [pysatochip](https://github.com/Toporin/pysatochip) v0.12.3
* Add pyopenssl dependency (needed to validate card authenticity with PKI)
* Add support for new features: card label & card authenticity
* Add support for the [Satochip card](https://satochip.io) v0.12
* This release is based on the version 4.2.6 of the original
  Electron-Cash client (commit d5217ed3e878bd56977181f022f9e5c43f449241)

### CODE REVIEW

**Comment by cculianu** [comment]
Hmm. Linux AppImage and Windows binaries build just fine against this commit, but macOS fails (but works on master). Here is the error I got:

```
💬 INFO:  Installing hardware wallet requirements...
Collecting btchip-python==0.1.31
  Using cached btchip-python-0.1.31.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting construct==2.10.59
  Using cached construct-2.10.59.tar.gz (55 kB)
  Preparing metadata (setup.py) ... done
Collecting Cython==0.29.21
  Using cached Cython-0.29.21-cp38-cp38-macosx_10_9_x86_64.whl (1.9 MB)
Collecting hidapi==0.10.1
  Using cached hidapi-0.10.1-cp38-cp38-macosx_10_9_x86_64.whl (44 kB)
Collecting keepkey==6.3.1
  Using cached keepkey-6.3.1-py3-none-any.whl (93 kB)
Collecting libusb1==1.9.1
  Using cached libusb1-1.9.1-py3-none-any.whl (58 kB)
Collecting mnemonic==0.19
  Using cached mnemonic-0.19-py2.py3-none-any.whl (61 kB)
Collecting pyopenssl==20.0.0
  Downloading pyOpenSSL-20.0.0-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 1.9 MB/s            
Collecting pysatochip==0.12.3
  Downloading pysatochip-0.12.3-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 7.1 MB/s             
Collecting pyscard==2.0.0
  Using cached pyscard-2.0.0-cp38-cp38-macosx_10_14_x86_64.whl (137 kB)
Collecting trezor==0.12.2
  Using cached trezor-0.12.2-py3-none-any.whl (307 kB)
Collecting typing-extensions==3.7.4.2
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Requirement already satisfied: setuptools>=19.0 in /Users/calin/Library/Python/3.8/lib/python/site-packages (from hidapi==0.10.1->-r ./contrib/deterministic-build/requirements-hw.txt (line 44)) (53.0.0)
Requirement already satisfied: ecdsa>=0.9 in /Users/calin/Library/Python/3.8/lib/python/site-packages (from keepkey==6.3.1->-r ./contrib/deterministic-build/requirements-hw.txt (line 66)) (0.16.1)
Requirement already satisfied: protobuf>=3.0.0 in /Users/calin/Library/Python/3.8/lib/python/site-packages (from keepkey==6.3.1->-r ./contrib/deterministic-build/requirements-hw.txt (line 66)) (3.14.0)
Requirement already satisfied: cryptography>=3.2 in /Users/calin/Library/Python/3.8/lib/python/site-packages (from pyopenssl==20.0.0->-r ./contrib/deterministic-build/requirements-hw.txt (line 81)) (3.3.1)
Requirement already satisfied: six>=1.5.2 in /Users/calin/Library/Python/3.8/lib/python/site-packages (from pyopenssl==20.0.0->-r ./contrib/deterministic-build/requirements-hw.txt (line 81)) (1.14.0)
Requirement already satisfied: pyaes==1.6.1 in /Users/calin/Library/Python/3.8/lib/python/site-packages (from pysatochip==0.12.3->-r ./contrib/deterministic-build/requirements-hw.txt (line 84)) (1.6.1)
Collecting ecdsa>=0.9
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    ecdsa>=0.9 from https://files.pythonhosted.org/packages/b8/11/4b4d30e4746584684c758d8f1ddc1fa5ab1470b6bf70bce4d9b235965e99/ecdsa-0.15-py2.py3-none-any.whl#sha256=867ec9cf6df0b03addc8ef66b56359643cb5d0c1dc329df76ba7ecfe256c8061 (from keepkey==6.3.1->-r ./contrib/deterministic-build/requirements-hw.txt (line 66))
WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the '/Users/calin/.pyenv/versions/3.8.9/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install --upgrade pip' command.
🗯  ERROR:  Could not install hardware wallet requirements
```

Looks like some dependency issue.. will try to resolve.

**Comment by cculianu** [comment]
@Toporin  See above ... any idea?

**Comment by cculianu** [comment]
Yeah it appears the requirements file for pysatochip v0.12.3 is buggy because it specifies exact versions using `==`. This is the commit that fixed it: https://github.com/Toporin/pysatochip/commit/616864c06c5c7348e1367bde00b52c4a50d116b6

However, v0.12.3 of pysatochip still uses that buggy requirements file.  I have fixed this on my end by telling pip `--no-deps` when installing the `requirements-hw.txt` file in the macOS build scripts, as a workaround, for now.

Looking forward to your PR to update Electron Cash to use a newer pysatochip some day...

**Comment by Toporin** [comment]
I think I found the issue:

The version v0.12.3 of Pysatochip requires the package ecdsa v0.15 (see https://github.com/Toporin/pysatochip/blob/85fafe07c2f445dae2508853e5c4da2450957e97/requirements.txt), but certificate pinning requires ecdsa v0.16.1 in requirements.txt.

So this is an issue with pysatochip 0.12.3 that forces the use of ecdsa v0.15.
This was corrected in the next commit (616864c06c5c7348e1367bde00b52c4a50d116b6) and the latest release of Pysatochip (v0.14.2) corrects this specific issue and should be ok (but I haven't tested yet). I will try to patch this ASAP (maybe release a v0.12.4?). 

Sorry about this :-s

**Comment by cculianu** [comment]
It's not critical. I just introduced a commit to ignore your deps. If you do patch it let me know and we can update the requirements files.

**Comment by cculianu** [comment]
Ok well I'm satisfied for now. Merging...

**Comment by Toporin** [comment]
FYI, I submitted a small PR that patches the issue with pysatochip v0.12.3 (see #2410)

**Pull request merged**
