### PR TITLE
Fix icon install directory and add install of svg icon

### PR DESCRIPTION
**Pull request by nopeinomicon**
Changed icon install directory to the proper one reflecting icon dimensions (256x256) and added install for the scalable icon.

### CODE REVIEW

**Comment by cculianu** [comment]
I have no idea if this is correct -- and lack the time to test this at the moment -- I'm going to go with my gut here and say that since you are a package maintainer you probably got it right. Merging.

**Comment by fyookball** [comment]
I have no idea if its correct either.  @nopeinomicon why is it ok that the 128 pixel directory is gone now?  Do some OS expect that?

**Comment by nopeinomicon** [comment]
> I have no idea if its correct either. @nopeinomicon why is it ok that the 128 pixel directory is gone now? Do some OS expect that?

I mean, that directory is a part of the hicolor icon theme, so this isn't what manages it anyway. The icon is a 256x256 image, meaning it should go in the 256x256 folder. I sussed that out because the rpm builder automatically detected that mismatch, so this is just here to fix that issue, and also add the svg icon to the scalable icon folder so it is available.

**Comment by cculianu** [comment]
@fyookball  -- Yeah it just seemed to get installed to the wrong place.  And now that Linux distros can accept SVG, I guess she added the svg as part of the install.... Seems legit.

**Pull request merged**
