### PR TITLE
Fonts: Improved emoji rendering consistency on Linux

### PR DESCRIPTION
**Pull request by EchterAgo**
We still need a detection for fontconfig >= 2.13, which breaks. I'll submit a PR for that tomorrow.

### CODE REVIEW

**Comment by EchterAgo** [comment]
Build hashes:

```
63d96d5bd2e321a807808c41053d4de7b28dc9a3e4386006f4b90ba1c18c3751  dist/Electron-Cash-4.0.8-dev1-12-g19e760ed2.exe
c3095bc3dcd8f185eecc689cfee6078d84ec0d516f0f179b8aa2f73f2f498569  dist/Electron-Cash-4.0.8-dev1-12-g19e760ed2-portable.exe
792a98421c709aa8b2cb8385ba2bab65edd8e17f05de22776b7becb344e4eb61  dist/Electron-Cash-4.0.8-dev1-12-g19e760ed2-setup.exe
5bbe4b331cb2757b722956b6ea1a0b3d0092e5df2f6cca9b6327c895e725f90d  dist/Electron-Cash-4.0.8-dev1-12-g19e760e-x86_64.AppImage
```

**Comment by EchterAgo** [comment]
Tested on:

* Arch Linux
* Centos 7
* Debian 9
* Debian 10
* Fedora 29
* Mint 19
* Tails 3.13
* Ubuntu 14.04
* Ubuntu 16.04
* Ubuntu 18.04
* Windows 10 1903
* Windows 10 1803

Still breaks with fontconfig 2.13 and newer

**Comment by cculianu** [comment]
Hey I added the detector and also separated out libfreetype and libfontconfig into 2 dirs.

- Fontconfig version threshold is `2.12.6` -- if system version is that or newer, we prefer system. 
- Freetype version threshold is `2.8.1` -- if system version is newer, we prefer system.
- AppRun now runs both the test scripts and sets LD_LIBRARY_PATH according to return results.

I won't merge this just yet in case  you have some final touches.

Note I got rid of the CentOS check.  I am optimistic maybe these changes make that check not needed.

**Comment by cculianu** [comment]
I'm just going to go ahead and merge this. We can worry about ironing out the final platform issues (if any) in another PR! :D

**Comment by EchterAgo** [comment]
This looks nice, going to test that.

**Pull request merged**
