### PR TITLE
Fix Appimage build files for deterministic build

### PR DESCRIPTION
**Pull request by tl121**
This pull request fixes non-repeatable builds of the Electron Cash Linux appimage by editing the source code of zxing-cpp to remove three occurrences of the  __FILE__ macro. Three security updates were also made to the Ubuntu 2004 Docker Image.

The App Image has been tested on Ubuntu 20.04, 22.04 and 23.10 with software wallets and with Trezor hardware wallets, including the Trezor Safe 3. The zxing-cpp QR functionality has not yet been tested as I do not currently have a Linux system with a camera.

### CODE REVIEW

**Comment by EchterAgo** [comment]
Thanks, this looks good. I also had another approach to sanitizing the paths that might be cleaner and which I want to get the `zxing-cpp` upstream to merge, which is using `-ffile-prefix-map` in `CMakeLists.txt`. I'll push a branch for this soon.

**Comment by EchterAgo** [comment]
There is still an issue with it which I need to solve, see https://github.com/zxing-cpp/zxing-cpp/pull/730

**Comment by EchterAgo** [comment]
Ok, I think I have the zxing issue fixed, I'll author a commit on top of this PR to use the fix and will test the AppImage with a camera.

**Comment by EchterAgo** [comment]
https://github.com/EchterAgo/Electron-Cash/commit/b6da2bde091c502f258c3fdb529a370147d100a4

If you want to cherry pick the commit I can also add a description.

**Comment by EchterAgo** [comment]
```
$ sha256sum dist/Electron-Cash-4.3.1-144-gb6da2bde0-x86_64.AppImage*
17889e8d600e81d65267b163a8bb094d33d134f8a97e1c3b541de522392ae6f6  dist/Electron-Cash-4.3.1-144-gb6da2bde0-x86_64.AppImage
17889e8d600e81d65267b163a8bb094d33d134f8a97e1c3b541de522392ae6f6  dist/Electron-Cash-4.3.1-144-gb6da2bde0-x86_64.AppImage.old
```

**Comment by EchterAgo** [comment]
I'm going to test the camera now. We can also merge this first and I'll make my update a separate PR.

**Comment by EchterAgo** [comment]
Can't test the camera yet, it seems there is something wrong with newer Ubuntu. It detects the camera but can not get the list of resolutions, it is always empty.

```
| 11.948| |MainThread| [QrReaderCameraDialog] camera status changed to loading
| 11.957| |MainThread| [QrReaderCameraDialog] camera status changed to loaded
| 11.961| |MainThread| [QrReaderCameraDialog] searching for at least 512x512
| 11.961| |MainThread| [QrReaderCameraDialog] camera resolutions:
| 11.961| |MainThread| [QrReaderCameraDialog] ideal resolutions: , less-than-ideal resolutions:
| 11.963| |MainThread| [QrReaderCameraDialog] closed
```

**Comment by EchterAgo** [comment]
```
| 11.153| |MainThread| [QrReaderCameraDialog] Failed to open selected camera, trying to use default camera

(gst-plugin-scanner:3383175): GStreamer-WARNING **: 22:37:28.786: Failed to load plugin '/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopengl.so': /tmp/.mount_ElectrjW54MN/usr/lib/x86_64-linux-gnu/libudev.so.1: version `LIBUDEV_247' not found (required by /lib/x86_64-linux-gnu/libgudev-1.0.so.0)

(gst-plugin-scanner:3383175): GStreamer-WARNING **: 22:37:28.822: Failed to load plugin '/lib/x86_64-linux-gnu/gstreamer-1.0/libgstaasink.so': /tmp/.mount_ElectrjW54MN/usr/lib/x86_64-linux-gnu/libtinfo.so.6: version `NCURSES6_TINFO_6.2.20211010' not found (required by /lib/x86_64-linux-gnu/libncurses.so.6)

(gst-plugin-scanner:3383175): GStreamer-WARNING **: 22:37:28.891: Failed to load plugin '/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvideo4linux2.so': /tmp/.mount_ElectrjW54MN/usr/lib/x86_64-linux-gnu/libudev.so.1: version `LIBUDEV_247' not found (required by /lib/x86_64-linux-gnu/libgudev-1.0.so.0)
| 11.324| |NetThread-4| [electrs.electroncash.de] server was verified correctly
```

This is a packaging problem and unrelated to your change.

**Comment by EchterAgo** [comment]
but even without udev in the package:

```
| 12.631| |MainThread| [QrReaderCameraDialog] Failed to open selected camera, trying to use default camera
| 13.947| |MainThread| [QrReaderCameraDialog] camera status changed to loading
| 13.953| |MainThread| [QrReaderCameraDialog] camera status changed to loaded
| 13.958| |MainThread| [QrReaderCameraDialog] searching for at least 512x512
| 13.958| |MainThread| [QrReaderCameraDialog] camera resolutions:
| 13.958| |MainThread| [QrReaderCameraDialog] ideal resolutions: , less-than-ideal resolutions:
| 13.960| |MainThread| [QrReaderCameraDialog] closed
```

I'm sure this is not because of your change though.

**Comment by tl121** [comment]
> Thanks, this looks good. I also had another approach to sanitizing the paths that might be cleaner and which I want to get the `zxing-cpp` upstream to merge, which is using `-ffile-prefix-map` in `CMakeLists.txt`. I'll push a branch for this soon.

Thank you.

I was getting builds that were unaffected by the build directory once the __FILE__ macro was removed from the three places in Error.h.  As a result, the EC appimage was reproducible, at least as far as I could test it (several times each
running out of different folders running the script.  So, unless I am mistaken it shouldn't be necessary to worry about the
upstream build process.

However, that said, if you can get the release code fixed upstream that's obviously better. 

 But the real problem is even more upstream, located in various places, such as the design of --fmacrio-prefix-map which only works if you know the prefix you are trying to eliminate coupled with the design of the Pip temporary directory process which gratuitously randomizes part of the file prefix and does not provide control over the randomness, coupled with the fairly recent change in Pip where the Pip powers that be removed the control over the build directory that would have eliminated the random directory creation.  And from leading various various discussions it appears that developers at various levels of the "stream"  have differing religious views. (Such is the nature of open source, at least there is no central controlling malevolent dictator.. :-) )

Since the random Pip build process controls the random directory path name that CMake works with, I don't see how changing the CMake process would help.  But perhaps there is a trick that I am missing, which wouldn't surprise me since all of this entire process was totally new to me until recently.  (Working with an unchanged zxing-cpp build process from the zxing-cpp I was able to use CXX_FLAGS to enable -fmacro-prefix-map to create reproducible output when running from github clones in dirrect local directories, but my script had access to all the necessary directory information.)

IMO the real problem is that the __FILE__ macro itself is really useful only for debug purposes and there should be a way to disable it  via CFLAGS.  Or if this would create too many problems, to add a wild card option to fmacro-prefix-map that matches the entire prefix so that CFLAGS can be used to control the entire FILE output  As is presently the case the only guaranteed match is to provide a  null string which allows adding to the beginning of the path, but this can't be used to eliminate the randomness.

**Comment by EchterAgo** [comment]
> Since the random Pip build process controls the random directory path name that CMake works with, I don't see how changing the CMake process would help.

But `cmake` does know all the directories involved and can definitely pass the right `-ffile-prefix-map`. Basically we're just telling it to strip out the random part produced by pip / distutils. With `set(FILE_PREFIX_ARG "-ffile-prefix-map=${CMAKE_CURRENT_SOURCE_DIR}=")` we only get paths relative to the source dir.

**Comment by cculianu** [comment]
Ok merging since Axel approved it.

**Pull request merged**
