### PR TITLE
Build: Protect against PGP keyserver poisoning attack

### PR DESCRIPTION
**Pull request by EchterAgo**
This patch removes the downloading of the Python release signing keys from keyservers. Instead we just import these from files in the repository. This speeds up the build and makes it more reliable.

The source of the release signing keys is:

https://www.python.org/downloads/#pubkeys

These keys might change in the future and the file has to be updated then, but that should only happen when we update our Python version.

See this link for details on the keyserver attack:

https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

### CODE REVIEW

**Comment by EchterAgo** [comment]
Oh, I also removed the ability to skip the signature check using `NOPGP=1` in the environment. I don't think we should allow it anymore because there is no speed benefit anymore. If anyone has a good reason to allow it I'll add it back.

**Comment by EchterAgo** [comment]
Don't merge this yet. Looks like there is an issue with the `pubkeys.txt` file on python.org.

https://github.com/python/pythondotorg/issues/1395

Maybe we should generate our own file?

**Comment by EchterAgo** [comment]
Seems to not be a problem:

https://mail.python.org/pipermail/python-list/2019-March/739793.html

**Comment by EchterAgo** [comment]
Actually this is a problem because we don't set trust on keys and just look for `VALIDSIG` in the gpg output, so we would accept signatures from those "totally legit" keys. I updated this to only include the GPG key of [Steve Dower (Python Release Signing)](https://keybase.io/stevedower/pgp_keys.asc?fingerprint=7ed10b6531d7c8e1bc296021fc624643487034e5) with fingerprint `7ED1 0B65 31D7 C8E1 BC29  6021 FC62 4643 4870 34E5` who is currently signing all the Windows binary releases.

**Comment by EchterAgo** [comment]
@cculianu @fyookball @markblundeberg please check that the contents of https://keybase.io/stevedower/pgp_keys.asc?fingerprint=7ed10b6531d7c8e1bc296021fc624643487034e5 match contrib/build-wine/pgp/7ed10b6531d7c8e1bc296021fc624643487034e5.asc

SHA256:
6540096672a54a25e30f37e8700b98a94ba79b047b96a38df91db798f94a38e9  contrib/build-wine/pgp/7ed10b6531d7c8e1bc296021fc624643487034e5.asc

**Comment by cculianu** [comment]
Hey man will look at this later today.  Thanks so much for taking care of this!

**Comment by cculianu** [comment]
Ok, I can verify that sha256sum matches the file, and that the file contains Steve Dower's key.

I didn't realize pgp could be so insecure. 32-bit keys? Really?! Jesus..

Thanks for taking care of this. Will merge after I can confirm it builds on my docker..

(still building)

**Pull request merged**
